### ISSUE TITLE
Can no longer exclude a file if it's within an included directory

### ISSUE THREAD

**Issue by ocean90** [wp-cli/i18n-command#102]
Since https://github.com/wp-cli/i18n-command/pull/87 using `--include="wp-admin/*` and `--exclude="wp-admin/includes/network.php"` doesn't exclude `wp-admin/includes/network.php` anymore. This is now different from `find`: ` find . -path "./wp-admin/*" ! -path "./wp-admin/includes/network.php"`.

Related chat on Slack: https://wordpress.slack.com/archives/C02RP4T41/p1540844767128500

**Comment by schlessera** [comment]
Fixed in #104
