### ISSUE TITLE
Better identify translator's comments in built files.

### ISSUE THREAD

**Issue by herregroen** [wp-cli/i18n-command#106]
Currently when parsing files built by WebPack some translator's comments aren't being picked up yet due to how webpack outputs these.

For example:
![image](https://user-images.githubusercontent.com/4620754/48265100-e7e3e900-e42b-11e8-88b5-ff5775116c72.png)

It seems WebPack will always attach comments to the previous statement rather than prepend them.

JS parsing should either be updated to correctly identify these translator's comments or it should be investigated if WebPack can be configured to correctly output comments and in this case documentation published on how to do this.

**Comment by swissspidy** [comment]
> JS parsing should either be updated to correctly identify these translator's comments or it should be investigated if WebPack can be configured to correctly output comments and in this case documentation published on how to do this.

I prefer the latter.

Even better would be if we could actually parse the _source_ files for core, otherwise the source code reference is pretty much useless for translators. But that's something for another issue :-)

**Comment by anomiex** [comment]
You might move the comment closer to the `__()` call to reduce the chances that it will get dropped or misplaced as the code is transformed.

So instead of
```jsx
// translators: Some comment
label={ sprintf( __( 'msgid', 'domain' ), arg ) }
```
try this instead
```jsx
label={
    // translators: Some comment
    sprintf( __( 'msgid', 'domain' ), arg )
}
```
or even this
```jsx
label={
    sprintf(
        // translators: Some comment
        __( 'msgid', 'domain' ),
        arg
    )
}
```
