### ISSUE TITLE
Invalid MD5 hashes in make-json command

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/i18n-command#120]
As reported in https://core.trac.wordpress.org/ticket/45488.

Have to check that we take the path into account when creating the MD5 hashes of the file names.

**Comment by schlessera** [comment]
@swissspidy It currently looks like this issue will be handled on the core side?

I'm asking because I'm wrapping up a release and wondering whether there's something re. this issue that needs to be in this release.

**Comment by swissspidy** [comment]
I finally got to test this with a custom plugin and [Traduttore](https://github.com/wearerequired/traduttore). The Traduttore plugin creates JSON files just like WordPress.org and it's being used successfully to translate some Gutenberg bloccks.

The plugin creates JSON files with identical MD5 hashes in the file names as `wp i18n make-json`.

Closing this issue for now.
