### ISSUE TITLE
POT file generated with this command produces an error with Transifex service related to plural forms

### ISSUE THREAD

**Issue by greatislander** [wp-cli/i18n-command#121]
This is a fairly specific issue, but hopefully someone knows something (if the problem is on our end, feel free to close).

We've been using POEdit to (re)generate the POT file for [Pressbooks](https://github.com/pressbooks/pressbooks) and we use [Transifex](https://transifex.com) to manage translations. I have been trying out the wp-cli `make-pot` command and I get this error from the Transifex CLI when trying to upload the resulting POT file:

```
Error received from server: Your source file is not a POT file and the translation file you're using has more than two plurals which is not supported.
```

I ran the command with these options from the plugin root:

```
wp i18n make-pot . languages/_pressbooks.pot --exclude="vendor,symbionts" --headers='{"Report-Msgid-Bugs-To":"https://github.com/pressbooks/pressbooks/"}'
```

I note that in the wp-cli generated file, the second `msgstr` is missing from plural strings:

```diff
#: inc/class-cloner.php:2045 inc/modules/import/wordpress/class-wxr.php:337
#, php-format
msgid "%s part"
msgid_plural "%s parts"
msgstr[0] ""
- msgstr[1] ""
```

Is this expected?

Thanks in advance for any information that might lead to resolution!

**Comment by swissspidy** [comment]
Thanks a lot for your report!

I'll try to verify this to see if it's an actual bug in the command (i.e. we print the wrong format) or if Transifex is perhaps too strict about this.

**Comment by greatislander** [comment]
Thanks @swissspidy. If I can provide reference files for testing I'm happy to do that too.

**Comment by swissspidy** [comment]
CC @ocean90

**Comment by swissspidy** [comment]
I was wondering what the old `makepot.php` script was doing, but `xgettext` is a better reference for sure.

Relevant code in the upstream library:

https://github.com/oscarotero/Gettext/blob/545f716f08338030d2d0d35a1835d04a9d4f18ed/src/Generators/Po.php#L62-L71

Since we already extend this class and the `toString()` method, this shouldn't be hard to fix.
