### ISSUE TITLE
Theme's style.css not detected when in a subdirectory

### ISSUE THREAD

**Issue by bradyvercher** [wp-cli/i18n-command#124]
I'm working on bundling this package as the engine for [node-wp-i18n](https://github.com/cedaro/node-wp-i18n/issues/20) (which is used by [grunt-wp-i18n](https://github.com/cedaro/grunt-wp-i18n/issues/80)), but am running into a few failing tests due to slight differences in the way they work.

WordPress supports [themes that are in a subdirectory](https://github.com/WordPress/WordPress/blob/master/wp-includes/theme.php#L510-L511) of the theme root directory, but this command doesn't detect `style.css` files that aren't in the theme root and doesn't include a way to specify where to find the main file with the package metadata.

There could potentially be multiple nested themes in a themes in a theme directory, which would pose a problem for automatically detecting the correct theme when running `wp i18n` from the theme root, but the most common use case is to use the root directory for development and config related files, with `style.css` and templates in a subdirectory. This structure can be found in the [Make](https://github.com/thethemefoundry/make) theme, [Sage](https://github.com/roots/sage), and [WP Rig](https://github.com/wprig/wprig).

[Here's the issue](https://github.com/cedaro/node-wp-i18n/issues/16) in node-wp-i18n where support was requested and added.

**Comment by swissspidy** [comment]
Huh, I knew I saw this code before but somehow surprised WordPress still supports that.

Should be as easy as updating `MakePotCommand::get_main_file_data()`. Doesn't hurt to refactor that method anyway.
