### ISSUE TITLE
Update MO files when purging

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/i18n-command#126]
When running `wp i18n make-json` with the `--purge` options, we currently modify the PO files without also updating the MO files (if they exist) afterwards.

Perhaps we should do this. Otherwise you have to do this manually for all updated PO files.

**Comment by schlessera** [comment]
What would make the most sense here?

1. Add a switch `--update-mo-files` and present a warning when this switch is not provided.
2. Just do it by default, with the need to specifically opt-out when not wanted.

**Comment by swissspidy** [comment]
Good question.

I don't know if people need/want to verify the PO files first after purging before creating the MO files. But given that the `purge` option is opt-out by default, I think we should make this opt-out as well.
