### ISSUE TITLE
Call to undefined function WP_CLI\I18n\mb_ereg() in phar

### ISSUE THREAD

**Issue by mokorana** [wp-cli/i18n-command#138]
wp i18n make-pot . languages/my-plugin.pot
Theme stylesheet detected.
PHP Fatal error:  Uncaught Error: Call to undefined function WP_CLI\I18n\mb_ereg() in phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/IterableCodeExtractor.php:145
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/IterableCodeExtractor.php(173): WP_CLI\I18n\PhpCodeExtractor::isExcluded(Object(SplFileInfo), Array)
#1 [internal function]: WP_CLI\I18n\PhpCodeExtractor::WP_CLI\I18n\{closure}(Object(SplFileInfo), '/var/www/html/g...', Object(RecursiveDirectoryIterator))
#2 [internal function]: CallbackFilterIterator->accept()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/IterableCodeExtractor.php(191): FilterIterator->rewind()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/IterableCodeExtractor.php(83): WP_CLI\I18n\PhpCodeExtractor::getFilesFromDirectory('/var/www/html/g...', Array, Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/MakePotCommand.php(529): WP_CLI\I18n\PhpCodeExtractor::fromDirectory('/var/www/html/g...', Object(Gettext\Translations), Arra in phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/IterableCodeExtractor.php on line 145

**Comment by danielbachhuber** [comment]
@swissspidy Do we have a dependency on `mb_ereg()` that we need to explicitly define?

**Comment by swissspidy** [comment]
Related: #117

We can probably rewrite things to not use `mb_ereg`. Would have to test this.

**Comment by UVLabs** [comment]
@swissspidy @danielbachhuber any update here? I'm getting the same error as OP...followed the guide here: https://developer.wordpress.org/cli/commands/i18n/make-pot/

**Comment by kraftner** [comment]
This errors appears if your PHP doesn't have multibyte string support enabled hence missing the `mb_ereg()` function.

For example on Debian Stretch you need to add this package: https://packages.debian.org/stretch/php/php7.0-mbstring

**Comment by betodasilva** [comment]
`sudo apt-get install php7.2-mbstring
`
This should make it work
