### ISSUE TITLE
i18n make-json fatal error under windows 10

### ISSUE THREAD

**Issue by idea--list** [wp-cli/i18n-command#139]
Hi there,

I began learning how to develop custom block plugins for GB just few days ago.
Of course i think all the plugins should be translation-ready out of the box, that is why it is one of the first things i want to implement in my GB plugins as well.

I followed the description found here: https://pascalbirchler.com/internationalization-in-wordpress-5-0/
wp i18n make-pot works just fine on my side. Can also create the .po and .mo files with poedit pro just as in plain PHP environment...

but then wp make-json just throws warnings and a fatal error, without creating the .json file.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/5784071/52243285-76f08800-28d9-11e9-840c-cce5683dc078.png)

I am developing on a Windows 10 Pro System (build 17763), with WAMP v3.1.4 installed on it. JSON module is enabled in PHP.

I read somewhere WP CLI has limited functionality on Windows, however i am not sure if that is the cause of the problem i am facing.

**Comment by swissspidy** [comment]
Hi there

This was recently fixed by #133 and will be included in the upcoming 2.1.1 release of WP-CLI.

Until that happens, to install the latest version of this package over what's included in WP-CLI, run:

```bash
wp package install git@github.com:wp-cli/i18n-command.git
```

**Comment by idea--list** [comment]
Thanks for the info swisspidy,

Will need to wait for the release as using your command just exhaust the memory of my computer even if i set memory_limit to 1G in PHP

**Comment by Ugoku** [comment]
@swissspidy I'm still running into this error, even after running the command you provided. FWIW, here's the command I run and the full output:

```
sander@recras-sander:~/src/recras-wordpress-plugin$ wp i18n make-json lang/recras-wp-nl_NL.po lang/
PHP Warning:  file_get_contents(phar:///usr/local/bin/wp/vendor/gettext/languages/src/cldr-data/main/en-US/languages.json): failed to open stream: phar error: "vendor/gettext/languages/src/cldr-data/main/en-US/languages.json" is not a file in phar "/usr/local/bin/wp" in phar:///usr/local/bin/wp/vendor/gettext/languages/src/CldrData.php on line 72
PHP Warning:  Invalid argument supplied for foreach() in phar:///usr/local/bin/wp/vendor/gettext/languages/src/CldrData.php on line 37
PHP Warning:  file_get_contents(phar:///usr/local/bin/wp/vendor/gettext/languages/src/cldr-data/main/en-US/territories.json): failed to open stream: phar error: "vendor/gettext/languages/src/cldr-data/main/en-US/territories.json" is not a file in phar "/usr/local/bin/wp" in phar:///usr/local/bin/wp/vendor/gettext/languages/src/CldrData.php on line 74
PHP Warning:  Invalid argument supplied for foreach() in phar:///usr/local/bin/wp/vendor/gettext/languages/src/CldrData.php on line 37
PHP Warning:  file_get_contents(phar:///usr/local/bin/wp/vendor/gettext/languages/src/cldr-data/supplemental/plurals.json): failed to open stream: phar error: "vendor/gettext/languages/src/cldr-data/supplemental/plurals.json" is not a file in phar "/usr/local/bin/wp" in phar:///usr/local/bin/wp/vendor/gettext/languages/src/CldrData.php on line 76
PHP Warning:  Invalid argument supplied for foreach() in phar:///usr/local/bin/wp/vendor/gettext/languages/src/CldrData.php on line 37
PHP Warning:  file_get_contents(phar:///usr/local/bin/wp/vendor/gettext/languages/src/cldr-data/main/en-US/scripts.json): failed to open stream: phar error: "vendor/gettext/languages/src/cldr-data/main/en-US/scripts.json" is not a file in phar "/usr/local/bin/wp" in phar:///usr/local/bin/wp/vendor/gettext/languages/src/CldrData.php on line 78
PHP Warning:  Invalid argument supplied for foreach() in phar:///usr/local/bin/wp/vendor/gettext/languages/src/CldrData.php on line 37
PHP Fatal error:  Uncaught InvalidArgumentException: The language "en" is not valid in phar:///usr/local/bin/wp/vendor/gettext/gettext/src/Translations.php:356
Stack trace:
#0 /home/sander/.wp-cli/packages/vendor/wp-cli/i18n-command/src/MakeJsonCommand.php(163): Gettext\Translations->setLanguage('en')
#1 /home/sander/.wp-cli/packages/vendor/wp-cli/i18n-command/src/MakeJsonCommand.php(97): WP_CLI\I18n\MakeJsonCommand->make_json('/home/sander/sr...', 'lang/')
#2 [internal function]: WP_CLI\I18n\MakeJsonCommand->__invoke(Array, Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(93): call_user_func(Array, Array, Array)
#4 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(449): call_user_func(Object(Closure), Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(366): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
 in phar:///usr/local/bin/wp/vendor/gettext/gettext/src/Translations.php on line 356
```

**Comment by manooweb** [comment]
@swissspidy many thanks. Update package - with composer - works fine for me and now ```wp i18n make-json languages``` command works fine too by waiting the next release of WP-CLI.

**Comment by mkaz** [comment]
@swissspidy I've ugpraded to wp cli 2.1.1 and wp cli 2.2.0 and I see the same error mentioned by above.

If I run the package command you provide, everything works as expected. So it doesn't seem like the right composer changes got into the release?

`wp package install git@github.com:wp-cli/i18n-command.git`

**Comment by schlessera** [comment]
@mkaz Could it be that you already had an older version of the `wp-cli/i18n-command` installed through the package manager?

**Comment by mkaz** [comment]
@schlessera Yes, it is possible. I just deleted completely and reinstalled and now everything seems to be working. It appears the self upgrade process did not upgrade properly, but not sure how to get back to the old state to test.

My goal is to confirm it works a default install, which I now have. So I can update the Gutenberg documentation to use the `make-json` instead of `po2json` here: https://wordpress.org/gutenberg/handbook/designers-developers/developers/internationalization/

Thanks for the help,
