### ISSUE TITLE
Gettext library requires PHP 5.4+

### ISSUE THREAD

**Issue by schlessera** [wp-cli/i18n-command#14]
As @gitlost had noted in https://github.com/wp-cli/makepot-command/pull/13#issuecomment-357454257 , the [Gettext](https://github.com/oscarotero/Gettext) library that the `makepot` command uses requires PHP 5.4+, which makes it unfit to be bundled with the current WP-CLI, with its PHP 5.3.29+ requirement.

Our current options:

* Fork the [`oscarotero/Gettext`](https://github.com/oscarotero/Gettext) library, make it PHP 5.3-compatible and submit PR to upstream (which is unlikely to be accepted)
* Fork the [`oscarotero/Gettext`](https://github.com/oscarotero/Gettext) library into our own org and maintain our own PHP 5.3-compatible branch
* Keep the `makepot` as a separate command for now and rediscuss bundling it with WP-CLI 2.0

@gitlost, @swissspidy thoughts?

**Comment by swissspidy** [comment]
We‘re not in a hurry to add this to WP-CLI, so version 2.0 makes sense to me.

**Comment by gitlost** [comment]
Version 2.0 sounds good to me too!

**Comment by danielbachhuber** [comment]
Just a heads up that `wp server` currently requires PHP 5.4+: https://github.com/wp-cli/server-command/blob/master/server-command.php#L12-L19

You could simply add an equivalent check if you wanted to include `wp makepot`

**Comment by schlessera** [comment]
Oh, yes, I like that. We can make the command available to "almost anyone" this way.
