### ISSUE TITLE
New command: make-mo

### ISSUE THREAD

**Issue by slaFFik** [wp-cli/i18n-command#141]
Some 3rd party translation services/solutions can provide a `.po` file only.
And a lot of manual work is needed to generate `.mo` files out of them (imagine several plugins translated into several languages - and multiple to get the number of `.mo` files needed to be generated manually).
It would be helpful, if there was a `wp i18n make-mo` command, that should accept the directory with `.po` files and output generated `.mo` files with the same name.

**Comment by swissspidy** [comment]
Related: #126

**Comment by EvanShaw** [comment]
@slaFFik You can accomplish what you're looking for with the following:
```sh
find ./languages -name "*.po" | sed 's/\.po//g' | xargs -I % msgfmt %.po -o %.mo
```
Of course, this solution assumes you're on a UNIX system and that you have `gettext` installed and in your PATH...

It would really be nice if there was a platform agnostic `make-mo` command. @swissspidy Is there any plan to make one?

**Comment by swissspidy** [comment]
@EvanShaw At the moment I personally don't have much time to look into this, but contributions would be always welcome :-) Otherwise we'll get to this eventually.

**Comment by slaFFik** [comment]
I think README.md should be updated as well with this new command.

**Comment by schlessera** [comment]
> I think README.md should be updated as well with this new command.
Yes, it should. I'm currently experimenting with automating this via a GitHub Actions workflow, so keeping this open for testing.
