### ISSUE TITLE
Extract strings from script elements in PHP files

### ISSUE THREAD

**Issue by cbratschi** [wp-cli/i18n-command#148]
As far as I can see the extractors only support string extraction from PHP code and standalone .js files. It would be useful to extract strings from JavaScript code embedded in PHP files too.

Example test.php:

```
...
<script>
    console.log(wp.i18n.__e('test', 'domain'));
</script>
...
```

**Comment by swissspidy** [comment]
Yeah, as far as I can tell the [upstream library](https://github.com/oscarotero/Gettext/) we use does not support this. Not sure how difficult it would be to extend it. Also, it's probably not a widely common use case I think.

As a workaround, you could just use PHP:

```
<script>
    console.log(<?php echo esc_js( __( 'test', 'domain' ) ); ?>);
</script>
```

(Note that `_e` is not a thing in `wp.i18n`)

**Comment by michaelzangl** [comment]
You should use the php version @swissspidy suggested, since the wp.i18n helpers require the script to be loaded with the correct wp_set_script_translations call. This requires a reference to a script file name.
