### ISSUE TITLE
make-json theme and WPML issues

### ISSUE THREAD

**Issue by cbratschi** [wp-cli/i18n-command#151]
We are getting closer in using `make-json` but there are still some obstacle while using it in our theme with WPML.

# WPML

First of all WPML registers the `load_script_translation_file` filter. Their code seems to redirect the call to load  `.json` language files from their folder and results in empty translation strings.

We disabled it with:

```php
remove_all_filters('load_script_translation_file');
```

This is a hack but now the JSON files are loaded.

# make-json output

The make-json command creates the following file:

`de_CH-1357317445a54b7e637b7de5e4a65533.json`

This one is not working. However, the following file works:

`my_theme-de_CH-page-language-test.json`

We tried to pass `--domain my_theme` to make-json but it fails with a format error:

```
    at formatError (/opt/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^3.7.0/format-error.js:20:10)
```

Is there a way to disable the MD5 postfix and use the handle? And how can we add the domain as prefix (note that in a theme there is no prefix to the .po files)?

**Comment by swissspidy** [comment]
> First of all WPML registers the `load_script_translation_file` filter.

Sounds like you should report this to WPML if this is causing issues.

> This one is not working. However, the following file works:

What's the path to the source JavaScript file? You should find it in the `source` entry in the JSON file.

If the path is wrong / unexpected, the MD5 hash is incorrect. Related: #127

> We tried to pass `--domain my_theme` to `make-json` but it fails with a format error:

That error comes from your Gulp script, not WP-CLI. I don't know about your setup, but perhaps you need to use something like `gulp <your-gulp-script> -- --domain my_theme`.

**Comment by cbratschi** [comment]
> > First of all WPML registers the `load_script_translation_file` filter.
> 
> Sounds like you should report this to WPML if this is causing issues.

Yes, we will report this soon.

> > This one is not working. However, the following file works:
> 
> What's the path to the source JavaScript file? You should find it in the `source` entry in the JSON file.
> 

Yes, the .po file contained an old path. The following version is correct:

```
#: js/page-language-test.js:3
msgid "Test text in JavaScript file (original)."
msgstr "Beispieltext und JavaScript Datei (Deutsch)."
```

Now it loads the manually prefixed file:  my_theme-de_CH-ea62d66227815fad9236dce331676e6c.json.

MD5 is from 'js/page-language-test.js'.

So this is now solved.

One comment to the registration:

```
    wp_register_script('page-language-test', get_template_directory_uri() . '/js/page-language-test.js', array('wp-i18n'), '1553543524');
    wp_set_script_translations('page-language-test', 'my_theme', get_template_directory() . '/languages');
    remove_all_filters('load_script_translation_file');
```

wp_set_script_translations() does not support get_template_directory_uri(). A local path has to be used.

> If the path is wrong / unexpected, the MD5 hash is incorrect. Related: #127
> 
> > We tried to pass `--domain my_theme` to `make-json` but it fails with a format error:
> 
> That error comes from your Gulp script, not WP-CLI. I don't know about your setup, but perhaps you need to use something like `gulp <your-gulp-script> -- --domain my_theme`.

Our gulp script uses node-wp-cli to run the command. There is a bug in node-wp-cli which returns an object with properties instead of an Error instance. The WP-CLI error message is:

```
unknown --domain parameter
```

The domain handling is the only remaining issue.

**Comment by swissspidy** [comment]
> wp_set_script_translations() does not support get_template_directory_uri(). A local path has to be used.

That is correct. As the documentation says:

`$path - Optional. The full file path to the directory containing translation files.`

> The domain handling is the only remaining issue.

Ah, gotcha. `wp i18n make-json` does indeed not support a `--domain` because it is actually not used. That is indeed problematic.

The script just turns `<source>.po` into `<source>-hash.json`, which does not work as you mentioned.

I think the solution here should be:

1. Check `--domain` argument for text domain
1. If not passed, check PO file for `X-Domain` header.
2. Prefix JSON file with text domain in case it is missing.

**Comment by swissspidy** [comment]
Closing in favor of #197
