### ISSUE TITLE
i18n make-pot : best way to generate correct strings for the make-json step

### ISSUE THREAD

**Issue by manooweb** [wp-cli/i18n-command#153]
For our need all works fine now with make-pot and make-json after upgrading as @swissspidy explained in #139 

I want to know the best way how to use these tools. I explain the context.

We just have a few translatable strings in our JS code but distributed in several components.
Two of them use a placeholder. Therefore we put a "translators:" comment as make-pot warned us.

Then we have two options.

The first one
- use make-pot in our source excluding our bunde built with webpack
- in this case we don't loose "translators:" comment in the generated pot file
- use make-json which generates 9 files ie one per component.
- wp_set_script_translations don't register all these files and no translation appears in our UI even if I put them in the global languages plugins folder

The second one
- use make-pot in including only our bunde built with webpack
- in this case we loose "translators:" comment in the generated pot file
- use make-json which generates only one file.
- wp_set_script_translations register well the file and translations is displayed well in UI

I think the first one is the best but it doesn' work well.

What am I missing ?

Many thanks
Regards

**Comment by michaelzangl** [comment]
This is how I do it:
* Use make-pot on the .php and .js source files (main.pot)
* Translate this .pot file (=> only the .po files are required)
* Use make-pot on the .php files (php.pot)
* Run webpack to transpile the javascript files. (out/app.js, out/....js) Make sure to add `reserved: ['__', '_n', '_x', '_nx']` to the mangle options.
* Use make-pot on the webpack output directory (js.pot)
* Now for every locale:
** run `msgmerge --quiet -o temp-php.po real-po-file.po php.pot`
** run  `msgfmt -o /.../languages/lang.mo temp-php.po`
** run `msgmerge --quiet -o temp-js.po real-po-file.po js.pot`
** run  `wp-cli make-json temp-js.po /.../languages --no-purge --allow-root`

**Comment by swissspidy** [comment]
> in this case we loose "translators:" comment in the generated pot file

One should indeed update webpack so that these comments are preserved
