### ISSUE TITLE
Improve JSX parsing

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/i18n-command#168]
I am using WP-CLI 2.2.0 and just ran `wp i18n make-pot` against https://github.com/google/site-kit-wp with the debug flag on.

For many of the JS files there were `Unterminated string` errors. To me that sounds like the JSX parsing in Peast is not bulletproof just yet.

I'll try to see if I can come up with some reproducible test cases.

**Comment by cliffordp** [comment]
@swissspidy - curious why closed

**Comment by swissspidy** [comment]
I've never managed to follow-up with some reproducible test cases showing where the parsing didn't work, so this ticket was never really actionable. Plus, there's no point in having a ticket here for things that needs to be fixed upstream in the Peast library.
