### ISSUE TITLE
Avoid large language file diffs on different filesystems by sorting translatable files

### ISSUE THREAD

**Issue by l3ku** [wp-cli/i18n-command#171]
## Feature Request

 

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

When working on translations with developers that have different operating systems, 
the `wp i18n makepot` command causes large diffs that make reviewing language changes more challenging. The reason for this is that the command relies on the order the files are returned by the filesystem, and different filesystem implementations on the different operating systems of developers return the files in an arbitrary order.

A verbose example of the situation:

1. The first developer on e.g. Mac OS X runs `wp i18n makepot` on his/her machine, creating the source code files are traversed in the order returned by the OS
2. The first developer commits to git
3. The second developer on Ubuntu clones the git repo, creates a new branch and adds a single translatable line
4. The second developer regenerates the `.pot` file with `wp i18n makepot`, adds a translation with Poedit and pushes his/her branch

The strings in the`.pot` file will be reordered totally, and as a result also the actual translations in the `.po` files will follow this same new order. Reviewing the translation will be difficult.

**Describe the solution you'd like**

Always sort the translatable file paths in alphabetic order so the file order will be identical on all machines.

**Comment by swissspidy** [comment]
Thanks for raising this!

Sounds like a reasonable thing to do.
