### ISSUE TITLE
Error: 'i18n' is not a registered wp command.

### ISSUE THREAD

**Issue by Seebz** [wp-cli/i18n-command#18]
After installing wp-cli using latest (1.5.0) `.deb build` from [builds repo](https://github.com/wp-cli/builds/tree/gh-pages/deb), I'm stuck with this error :
`Error: 'i18n' is not a registered wp command. See 'wp help' for available commands.`

I tried an older package (1.3.0) but the problem is also present.

```
sebastien@computer:~$ wp --info
OS:	Linux 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.22-0ubuntu0.16.04.1
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/sebastien
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.5.0
```

```
sebastien@computer:~$ wp i18n
Warning: No WordPress install found. If the command 'i18n' is in a plugin or theme, pass --path=`path/to/wordpress`.
Error: 'i18n' is not a registered wp command. See 'wp help' for available commands.

sebastien@computer:~/www/wordpress$ wp i18n
Error: 'i18n' is not a registered wp command. See 'wp help' for available commands.
```

```
sebastien@computer:~$ uname -a
Linux computer 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

sebastien@computer:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

Note: the command `wp package install git@github.com:wp-cli/i18n-command.git` won't works too (it generates other error message) and [Travis](https://travis-ci.org/wp-cli/i18n-command) seems to be angry with latest commits.

So I suppose a problem from here...

**Comment by swissspidy** [comment]
This command is not part of WP-CLI 1.50, so the error message is correct. The command doesn't exist.

The error you get with `wp package install git@github.com:wp-cli/i18n-command.git` is more interesting tough. That shouldn't happen. Can you copy the message for us?

The travis errors are false positives, you can ignore them.

**Comment by Seebz** [comment]
> This command is not part of WP-CLI 1.50, so the error message is correct. The command doesn't exist.

It would be good to update the [Install instruction](https://github.com/wp-cli/i18n-command#installing), especially the following phrase :
> This package is included with WP-CLI itself, no additional installation necessary.

**Comment by swissspidy** [comment]
We could re-run the scaffolding here to mark the package as non-bundled.

Last time the goal was to bundle the command with the next release of WP-CLI, so I'm not sure it's necessary to do change the readme until then.

The command isn't really advertised anywhere so it's unlikely to be found by many people. And if they do, there's an installation hint in the readme.

**Comment by schlessera** [comment]
Yes, I agree, not worth bothering with an update now. I'd prefer working on getting this into nightly instead.

**Comment by tfritsch-km** [comment]
> The command isn't really advertised anywhere so it's unlikely to be found by many people. And if they do, there's an installation hint in the readme.

Yeah maybe not **many** people, but those who need it may find it (like I just did following a message of you @swissspidy : https://github.com/wp-cli/ideas/issues/68). 😃 The hint in the readme is also confusing because it looks like a way to upgrade the command, not install it from scratch. 

Maybe that a readme with correct install instructions (until the command is effectively merged into WP CLI) could help those for whom this command is made not losing their time trying a wrong use ?

thanks
