### ISSUE TITLE
Breaking signature change in `FunctionsScanner` interface

### ISSUE THREAD

**Issue by schlessera** [wp-cli/i18n-command#181]
## Bug Report

**Describe the current, buggy behavior**

The `gettext/gettext` library had a breaking change in its latest 4.7.0 release.

The `GetText\Utils\FunctionsScanner` abstract class had the signature for `saveGettextFunctions()` changed: https://github.com/oscarotero/Gettext/pull/223/files#diff-c39a8ad8478657b8b63da0ab3efb8ee0R28

This is currently throwing PHP strict notices and breaking our tests: https://travis-ci.org/wp-cli/i18n-command/jobs/598868700#L649

**Provide a possible solution**

We should bump the required version criteria for `gettext/gettext` to `^4.7` and adapt our signatures for the extended class(es).

**Comment by marcotaranta** [comment]
Hello! Can I have that issue?

**Comment by schlessera** [comment]
@marcotaranta Go for it!

**Comment by schlessera** [comment]
Fixed via #194
