### ISSUE TITLE
include argument is ignored

### ISSUE THREAD

**Issue by ocean90** [wp-cli/i18n-command#186]
While debugging #185 I came across another issue which was working previously in 2.2.0.

```
wp i18n make-pot /wordpress/trunk /wp-pot/trunk/wordpress-continents-cities.pot --include=wp-admin/includes/continents-cities.php
```

This should only parse `wp-admin/includes/continents-cities.php` but now WP-CLI is parsing everything (which is not excluded by the default rules).

The same happens for:

```
wp i18n make-pot /wordpress/trunk /wp-pot/trunk/wordpress-admin.pot --exclude=wp-admin/includes/continents-cities.php --include=wp-admin/*
```

It should only parse files in wp-admin and not also wp-content/wp-includes/etc.

**Comment by ocean90** [comment]
[Based on the lock file](https://github.com/wp-cli/wp-cli-bundle/blob/v2.2.0/composer.lock#L2065-L2077), 2.2.0 bundles v2.1.2 of this command which gives us this [changelog](https://github.com/wp-cli/i18n-command/compare/v2.1.2...master). #175 seems to be related.

**Comment by ocean90** [comment]
#262 didn't fix the first case for `continents-cities.php`. Debug output:

```
Debug (bootstrap): Running command: i18n make-pot (0.981s)
Debug (make-pot): No valid theme stylesheet or plugin file found, treating as a regular project. (0.987s)
Debug (make-pot): Extracting all strings regardless of text domain (0.987s)
Debug (make-pot): Destination: /home/wporgdev/co/wp-pot/trunk/wordpress-continents-cities.pot (0.988s)
Debug (make-pot): Only including the following files: wp-admin/includes/continents-cities.php (0.988s)
Debug (make-pot): Excluding the following files: node_modules,.git,.svn,.CVS,.hg,vendor,Gruntfile.js,webpack.config.js,*.min.js (0.989s)
Debug (make-pot): Parsing file index.php (1.932s)
Debug (make-pot): Parsing file wp-activate.php (1.933s)
Debug (make-pot): Parsing file wp-admin/about.php (1.943s)
Debug (make-pot): Parsing file wp-admin/admin-ajax.php (1.95s)
Debug (make-pot): Parsing file wp-admin/admin-footer.php (1.955s)
Debug (make-pot): Parsing file wp-admin/admin-functions.php (1.957s)
Debug (make-pot): Parsing file wp-admin/admin-header.php (1.958s)
Debug (make-pot): Parsing file wp-admin/admin-post.php (1.966s)
Debug (make-pot): Parsing file wp-admin/admin.php (1.968s)
Debug (make-pot): Parsing file wp-admin/async-upload.php (1.98s)
// Snip
```

**Comment by swissspidy** [comment]
@ocean90 So you ran the first command from above?

**Comment by swissspidy** [comment]
If so, did you try adding excludes to it?

**Comment by ocean90** [comment]
> @ocean90 So you ran the first command from above?

Correct, this one: https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-gp-customizations/inc/cli/class-make-core-pot.php?rev=10063&marks=67-84#L67

**Comment by ocean90** [comment]
I might be possible that I had a conflict with my custom build, on second try it seems to work now.

**Comment by swissspidy** [comment]
Awesome. Closing again then.

If there's still an issue, just let me know!
