### ISSUE TITLE
Still getting "Success: Created 0 files" in version 2.3.0 (latest i18n)

### ISSUE THREAD

**Issue by ole1986** [wp-cli/i18n-command#188]
## Bug Report

wp i18n make-json my-lang-de_DE.po /tmp/ --no-purge --debug
Debug (bootstrap): Loading packages from: /root/.wp-cli/packages/vendor/autoload.php (0.014s)
Debug (bootstrap): Loading detected autoloader: /root/.wp-cli/packages/vendor/autoload.php (0.029s)
Debug (commands): Adding command: i18n (0.032s)
Debug (commands): Adding command: make-pot in i18n Namespace (0.035s)
Debug (commands): Adding command: make-json in i18n Namespace (0.035s)
Debug (bootstrap): Fallback autoloader paths: phar://wp-cli.phar/vendor/autoload.php (0.035s)
Debug (bootstrap): Loading detected autoloader: phar://wp-cli.phar/vendor/autoload.php (0.035s)
Debug (commands): Adding command: cache (0.037s)
Debug (commands): Adding command: transient (0.039s)
Debug (commands): Adding command: comment (0.041s)
Debug (commands): Adding command: meta in comment Namespace (0.042s)
Debug (commands): Adding command: menu (0.042s)
Debug (commands): Adding command: item in menu Namespace (0.043s)
Debug (commands): Adding command: location in menu Namespace (0.043s)
Debug (commands): Deferring command: network meta (0.044s)
Debug (commands): Adding command: option (0.045s)
Debug (commands): Adding command: post (0.046s)
Debug (commands): Adding command: meta in post Namespace (0.046s)
Debug (commands): Adding command: term in post Namespace (0.047s)
Debug (commands): Adding command: post-type (0.047s)
Debug (commands): Adding command: site (0.049s)
Debug (commands): Adding command: meta in site Namespace (0.049s)
Debug (commands): Adding command: option in site Namespace (0.05s)
Debug (commands): Adding command: taxonomy (0.05s)
Debug (commands): Adding command: term (0.052s)
Debug (commands): Adding command: meta in term Namespace (0.053s)
Debug (commands): Adding command: user (0.07s)
Debug (commands): Adding command: meta in user Namespace (0.071s)
Debug (commands): Adding command: session in user Namespace (0.071s)
Debug (commands): Adding command: term in user Namespace (0.072s)
Debug (commands): Adding command: network (0.072s)
Debug (hooks): Processing hook "after_add_command:network" with 1 callbacks (0.072s)
Debug (hooks): On hook "after_add_command:network": Closure in file phar:///home/clients/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 634 (0.072s)
Debug (commands): Adding command: meta in network Namespace (0.072s)
Debug (commands): Adding command: db (0.075s)
Debug (commands): Adding command: plugin (0.079s)
Debug (commands): Adding command: theme (0.082s)
Debug (commands): Adding command: mod in theme Namespace (0.084s)
Debug (commands): Adding command: scaffold (0.087s)
Debug (commands): Adding command: core (0.087s)
Debug (commands): Adding command: verify-checksums in core Namespace (0.09s)
Debug (commands): Adding command: verify-checksums in plugin Namespace (0.091s)
Debug (commands): Adding command: export (0.091s)
Debug (commands): Adding command: config (0.105s)
Debug (commands): Adding command: core (0.113s)
Debug (commands): Adding command: eval (0.115s)
Debug (commands): Adding command: eval-file (0.115s)
Debug (commands): Adding command: import (0.116s)
Debug (commands): Adding command: media (0.14s)
Debug (commands): Adding command: package (0.143s)
Debug (commands): Adding command: cron (0.143s)
Debug (commands): Adding command: event in cron Namespace (0.144s)
Debug (commands): Adding command: schedule in cron Namespace (0.145s)
Debug (commands): Adding command: embed (0.145s)
Debug (commands): Adding command: fetch in embed Namespace (0.146s)
Debug (commands): Adding command: provider in embed Namespace (0.146s)
Debug (commands): Adding command: handler in embed Namespace (0.146s)
Debug (commands): Adding command: cache in embed Namespace (0.147s)
Debug (commands): Deferring command: language core (0.148s)
Debug (commands): Deferring command: language plugin (0.148s)
Debug (commands): Deferring command: language theme (0.15s)
Debug (hooks): Immediately invoking on passed hook "after_add_command:site": Closure in file phar:///home/clients/wp-cli/wp-cli.phar/vendor/wp-cli/language-command/language-command.php at line 39 (0.15s)
Debug (commands): Adding command: switch-language in site Namespace (0.15s)
Debug (commands): Adding command: language (0.15s)
Debug (hooks): Processing hook "after_add_command:language" with 3 callbacks (0.15s)
Debug (hooks): On hook "after_add_command:language": Closure in file phar:///home/clients/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 634 (0.15s)
Debug (commands): Adding command: core in language Namespace (0.15s)
Debug (hooks): On hook "after_add_command:language": Closure in file phar:///home/clients/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 634 (0.15s)
Debug (commands): Adding command: plugin in language Namespace (0.15s)
Debug (hooks): On hook "after_add_command:language": Closure in file phar:///home/clients/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 634 (0.15s)
Debug (commands): Adding command: theme in language Namespace (0.151s)
Debug (commands): Adding command: maintenance-mode (0.151s)
Debug (commands): Adding command: rewrite (0.152s)
Debug (commands): Adding command: rewrite (0.152s)
Debug (commands): Adding command: cap (0.153s)
Debug (commands): Adding command: role (0.154s)
Debug (commands): Adding command: search-replace (0.156s)
Debug (commands): Adding command: server (0.157s)
Debug (commands): Adding command: shell (0.162s)
Debug (commands): Adding command: super-admin (0.162s)
Debug (commands): Adding command: widget (0.163s)
Debug (commands): Adding command: sidebar (0.163s)
Debug (bootstrap): Adding framework command: phar://wp-cli.phar/vendor/wp-cli/wp-cli/php/commands/cli.php (0.164s)
Debug (commands): Adding command: cli (0.166s)
Debug (commands): Adding command: cache in cli Namespace (0.166s)
Debug (commands): Adding command: alias in cli Namespace (0.166s)
Debug (bootstrap): Adding framework command: phar://wp-cli.phar/vendor/wp-cli/wp-cli/php/commands/help.php (0.166s)
Debug (commands): Adding command: help (0.167s)
Debug (bootstrap): No readable global config found (0.167s)
Debug (bootstrap): No project config found (0.167s)
Debug (bootstrap): argv: /home/clients/wp-cli/wp-cli.phar --allow-root i18n make-json wp-ispconfig3-block-de_DE.po /tmp/ --no-purge --debug (0.167s)
Debug (bootstrap): ABSPATH defined: /home/clients/client42/web45/web/ (0.167s)
Debug (hooks): Processing hook "before_run_command" with 1 callbacks (0.167s)
Debug (hooks): On hook "before_run_command": WP_CLI\Bootstrap\RegisterDeferredCommands->add_deferred_commands() (0.167s)
Debug (bootstrap): Running command: i18n make-json (0.167s)
Success: Created 0 files.

**Comment by swissspidy** [comment]
Could you share the relevant translation file so we can test this ourselves?

**Comment by JHeimbach** [comment]
@ole1986 

make2json extracts only strings that are found in .js files. It uses the Reference comment of the .po files.

Therefore you have these references in your .po file.

For Example 
```
#: example.js:9
msgid "domain_name"
msgstr "Domain name"
````

With the default command make-json extracts these values to the json file. if you want that the messages in your po file are not removed, use the `--no-purge` flag.

Hope that helps.

**Comment by ole1986** [comment]
--no-purge parameter does not work as expected
