### ISSUE TITLE
How to update existing PO files?

### ISSUE THREAD

**Issue by strarsis** [wp-cli/i18n-command#189]
So `wp i18n make-pot` can generate a POT file. 
From this `POT` file a `PO` file can be derived that can be translated.
How can existing `PO` files be updated, too?
Is it possible to let `wp i18n make-pot` add the right settings and paths to 
the `POT` file to allow a tool like e.g. POEdit to update the strings in a derived `PO` file?

**Comment by swissspidy** [comment]
What kind of "right settings and paths" would need to be added for that?

AFAIK you can just edit a PO file in POEdit and then choose "Update from POT file" and pick the POT file from your computer to update from.

**Comment by sanzeeb3** [comment]
Hey @swissspidy - Just like `grunt-wp-i18n` has  an option to add `updatePoFiles: true` and all existing .po files will be automatically updated based on new .pot file. Is there a similar way to do with `wp i18n`? Editing every PO file in POEdit is tedious.
