### ISSUE TITLE
Error after clean install

### ISSUE THREAD

**Issue by Seebz** [wp-cli/i18n-command#19]
Hi, I just installed this package using the following command :

> sebastien@computer:~$ wp package install git@github.com:wp-cli/i18n-command.git
> Installing package wp-cli/i18n-command (dev-master)
> Updating /home/sebastien/.wp-cli/packages/composer.json to require the package...
> Registering git@github.com:wp-cli/i18n-command.git as a VCS repository...
> Using Composer to install the package...
> \---
> Loading composer repositories with package information
> Updating dependencies
> Resolving dependencies through SAT
> Dependency resolution completed in 0.630 seconds
> Analyzed 5408 packages to resolve dependencies
> Analyzed 311465 rules to resolve dependencies
> Package operations: 3 installs, 0 updates, 0 removals
> Installs: gettext/languages:2.3.0, gettext/gettext:v4.4.3, wp-cli/i18n-command:dev-master 93c1109
>  - Installing gettext/languages (2.3.0)
>  - Warning: gettext/gettext v4.4.3 requires gettext/languages ^2.3 -> satisfiable by gettext/languages[2.3.0].
>  - Installing gettext/gettext (v4.4.3)
>  - Warning: wp-cli/i18n-command dev-master requires gettext/gettext ^4.4 -> satisfiable by gettext/gettext[v4.4.0, v4.4.1, v4.4.2, v4.4.3].
>  - Installing wp-cli/i18n-command (dev-master 93c1109)
> Writing lock file
> Generating autoload files
> \---
> Success: Package installed.

---

But when I want to use it, I got this error message :

> sebastien@computer:~$ wp i18n
> Error: Callable "\\WP_CLI\\I18n\\Command_Namespace" does not exist, and cannot be registered as `wp i18n`.

---

Here the tree of my `.wp-cli` folder :

> sebastien@computer:~$ find .wp-cli -type d
> .wp-cli
> .wp-cli/packages
> .wp-cli/packages/vendor
> .wp-cli/packages/vendor/bin
> .wp-cli/packages/vendor/wp-cli
> .wp-cli/packages/vendor/wp-cli/i18n-command
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/info
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs/refs
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs/refs/heads
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs/refs/remotes
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs/refs/remotes/origin
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/logs/refs/remotes/composer
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/branches
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs/tags
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs/heads
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs/remotes
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs/remotes/origin
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/refs/remotes/composer
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/objects
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/objects/pack
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/objects/info
> .wp-cli/packages/vendor/wp-cli/i18n-command/.git/hooks
> .wp-cli/packages/vendor/wp-cli/i18n-command/features
> .wp-cli/packages/vendor/wp-cli/i18n-command/features/steps
> .wp-cli/packages/vendor/wp-cli/i18n-command/features/extra
> .wp-cli/packages/vendor/wp-cli/i18n-command/features/bootstrap
> .wp-cli/packages/vendor/wp-cli/i18n-command/src
> .wp-cli/packages/vendor/wp-cli/i18n-command/bin
> .wp-cli/packages/vendor/wp-cli/i18n-command/utils
> .wp-cli/packages/vendor/wp-cli/i18n-command/.github
> .wp-cli/packages/vendor/gettext
> .wp-cli/packages/vendor/gettext/gettext
> .wp-cli/packages/vendor/gettext/gettext/.git
> .wp-cli/packages/vendor/gettext/gettext/.git/info
> .wp-cli/packages/vendor/gettext/gettext/.git/logs
> .wp-cli/packages/vendor/gettext/gettext/.git/logs/refs
> .wp-cli/packages/vendor/gettext/gettext/.git/logs/refs/heads
> .wp-cli/packages/vendor/gettext/gettext/.git/logs/refs/remotes
> .wp-cli/packages/vendor/gettext/gettext/.git/logs/refs/remotes/origin
> .wp-cli/packages/vendor/gettext/gettext/.git/logs/refs/remotes/composer
> .wp-cli/packages/vendor/gettext/gettext/.git/branches
> .wp-cli/packages/vendor/gettext/gettext/.git/refs
> .wp-cli/packages/vendor/gettext/gettext/.git/refs/tags
> .wp-cli/packages/vendor/gettext/gettext/.git/refs/heads
> .wp-cli/packages/vendor/gettext/gettext/.git/refs/remotes
> .wp-cli/packages/vendor/gettext/gettext/.git/refs/remotes/origin
> .wp-cli/packages/vendor/gettext/gettext/.git/refs/remotes/composer
> .wp-cli/packages/vendor/gettext/gettext/.git/objects
> .wp-cli/packages/vendor/gettext/gettext/.git/objects/pack
> .wp-cli/packages/vendor/gettext/gettext/.git/objects/info
> .wp-cli/packages/vendor/gettext/gettext/.git/hooks
> .wp-cli/packages/vendor/gettext/gettext/src
> .wp-cli/packages/vendor/gettext/gettext/src/Utils
> .wp-cli/packages/vendor/gettext/gettext/src/Generators
> .wp-cli/packages/vendor/gettext/gettext/src/Extractors
> .wp-cli/packages/vendor/gettext/gettext/tests
> .wp-cli/packages/vendor/gettext/gettext/tests/assets
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/phpcode
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/twig
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/jscode
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/po2
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/po
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/phpcode2
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/blade
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/po3
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/jscode2
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/phpcode3
> .wp-cli/packages/vendor/gettext/gettext/tests/assets/jed
> .wp-cli/packages/vendor/gettext/languages
> .wp-cli/packages/vendor/gettext/languages/.git
> .wp-cli/packages/vendor/gettext/languages/.git/info
> .wp-cli/packages/vendor/gettext/languages/.git/logs
> .wp-cli/packages/vendor/gettext/languages/.git/logs/refs
> .wp-cli/packages/vendor/gettext/languages/.git/logs/refs/heads
> .wp-cli/packages/vendor/gettext/languages/.git/logs/refs/remotes
> .wp-cli/packages/vendor/gettext/languages/.git/logs/refs/remotes/origin
> .wp-cli/packages/vendor/gettext/languages/.git/logs/refs/remotes/composer
> .wp-cli/packages/vendor/gettext/languages/.git/branches
> .wp-cli/packages/vendor/gettext/languages/.git/refs
> .wp-cli/packages/vendor/gettext/languages/.git/refs/tags
> .wp-cli/packages/vendor/gettext/languages/.git/refs/heads
> .wp-cli/packages/vendor/gettext/languages/.git/refs/remotes
> .wp-cli/packages/vendor/gettext/languages/.git/refs/remotes/origin
> .wp-cli/packages/vendor/gettext/languages/.git/refs/remotes/composer
> .wp-cli/packages/vendor/gettext/languages/.git/objects
> .wp-cli/packages/vendor/gettext/languages/.git/objects/pack
> .wp-cli/packages/vendor/gettext/languages/.git/objects/info
> .wp-cli/packages/vendor/gettext/languages/.git/hooks
> .wp-cli/packages/vendor/gettext/languages/src
> .wp-cli/packages/vendor/gettext/languages/src/cldr-data
> .wp-cli/packages/vendor/gettext/languages/src/cldr-data/main
> .wp-cli/packages/vendor/gettext/languages/src/cldr-data/main/en-US
> .wp-cli/packages/vendor/gettext/languages/src/cldr-data/supplemental
> .wp-cli/packages/vendor/gettext/languages/src/Exporter
> .wp-cli/packages/vendor/gettext/languages/bin
> .wp-cli/packages/vendor/gettext/languages/tests
> .wp-cli/packages/vendor/gettext/languages/tests/Get
> .wp-cli/packages/vendor/gettext/languages/tests/Rules
> .wp-cli/packages/vendor/composer

**Comment by Seebz** [comment]
My config :

> sebastien@computer:~$ apt-cache policy php-wpcli 
> php-wpcli:
>   Installé : 1.5.0
>   Candidat : 1.5.0
>  Table de version :
>  *** 1.5.0 100
>         100 /var/lib/dpkg/status


> sebastien@computer:\~$ wp --info
> OS:	Linux 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64
> Shell:	/bin/bash
> PHP binary:	/usr/bin/php7.0
> PHP version:	7.0.22-0ubuntu0.16.04.1
> php.ini used:	/etc/php/7.0/cli/php.ini
> WP-CLI root dir:	phar://wp-cli.phar
> WP-CLI vendor dir:	phar://wp-cli.phar/vendor
> WP_CLI phar path:	/home/sebastien
> WP-CLI packages dir:	/home/sebastien/.wp-cli/packages/
> WP-CLI global config:	
> WP-CLI project config:	
> WP-CLI version:	1.5.0


> sebastien@computer:\~$ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.3 LTS
> Release:	16.04
> Codename:	xenial
>

**Comment by swissspidy** [comment]
Ah, `I18n_Namespace.php` should be `Command_Namespace.php`

**Comment by schlessera** [comment]
I think it should rather be file:`I18n_Command_Namespace.php` => class:`I18n_Command_Namespace` class.

**Comment by schlessera** [comment]
Ah, no, scrap that, as we're using namespaces. `CommandNamespace` would be my option (or with the underscore if you prefer to stay more WordPress-y).
