### ISSUE TITLE
Allow other file extensions

### ISSUE THREAD

**Issue by strarsis** [wp-cli/i18n-command#191]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

`make-pot` should allow configurable extension for the files to scan.
E.g. when the theme uses the [blade template language](https://laravel.com/docs/5.8/blade) (like the [roots.io Sage](https://roots.io/sage/) theme), many files will have the extension `blade.php` instead just `php`. Currently `make-pot` ignores these and the translations strings in the POT file are missing.

**Describe the solution you'd like**
A configuration option for the `make-pot` command for specifying different/more extension of the files to scan.

**Comment by strarsis** [comment]
Actually for support of files with multiple file extensions (as `blade.php` for PHP-Blade files), the `IterableCodeExtractor` filter has to be refactored, see this PR for PHP-Blade templates: https://github.com/wp-cli/i18n-command/pull/304

**Comment by swissspidy** [comment]
Closing this since dedicated Blade support was added in #304.

If it turns out that such configuration is needed for other file types, we can reopen it.
