### ISSUE TITLE
Error: Callable "\\WP_CLI\\I18n\\Command_Namespace" does not exist

### ISSUE THREAD

**Issue by EliaBR** [wp-cli/i18n-command#20]
Hi! After installing the package with `wp package install git@github.com:wp-cli/i18n-command.git`  and received a `Success: Package installed.` message, running `wp i18n` produced `Error: Callable "\\WP_CLI\\I18n\\Command_Namespace" does not exist, and cannot be registered as ``wp i18n``.`

Commenting the 14th line of i18n-command.php ( `WP_CLI::add_command( 'i18n', '\WP_CLI\I18n\Command_Namespace' );`) seemed to solve the problem for me, but I really don't know if it's the best way to make it.

Thanks a lot!

**Comment by swissspidy** [comment]
Yeah we need to rename a file there :-)

I‘ll try to fix it today.

See #19.
