### ISSUE TITLE
make-pot: `PO-Revision-Date` in header is incorrect

### ISSUE THREAD

**Issue by cliffordp** [wp-cli/i18n-command#202]
**Describe the current, buggy behavior**

Here's what gets generated with no `--headers` set:
![image](https://user-images.githubusercontent.com/1812179/75411259-3862ac80-58e4-11ea-94d9-fc12ec4cdac3.png)

* `PO-Revision-Date` should match the value of `POT-Creation-Date` if it's a new file.
* If the PO file is pre-existing, the `POT-Creation-Date` should be read and kept in the newly-generated file, but the `PO-Revision-Date` should be the current time.

**Describe how other contributors can replicate this bug**

`wp i18n make-pot .`

**Let us know what environment you are running this on**

![image](https://user-images.githubusercontent.com/1812179/75411501-0ef65080-58e5-11ea-94de-db8508b11f9f.png)

**Comment by swissspidy** [comment]
It‘s a POT file, not a PO file, as such the PO Revision  Date header is set as a placeholder. That is intentional.

**Comment by cliffordp** [comment]
@swissspidy thanks for the quick reply.

So if I'm creating a plugin and only generating the .pot, letting people do their own mo/po (it's not on .org and doesn't have a custom glotpress), then should I remove this header property, leave it blank, set the date to to match `POT-Creation-Date`, or leave the placeholder this command generates?

**Comment by swissspidy** [comment]
You would leave this in the POT file as-is.

It will be filled by the PO file editor when you save the PO file. So if someone starts creating a PO file based off the POT template (e.g. using POEdit), their PO file would get a current `PO-Revision-Date` header. The POT file would be left untouched.

This is how this field is defined by the gettext format, see https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html

**Comment by cliffordp** [comment]
That was helpful. Thank you very much.

While I have you... ;)
In this scenario, where I provide the .pot but not the actual translations, should I leave `Last-Translator` and `Language-Team` blank or still fill in my information?

**Comment by swissspidy** [comment]
Leave those blank as well. Those are also fields the folks creating the actual PO file would add. After all, those fields are specific to the locale the software is being translated in. Not the catalogue (POT) file.

**Comment by cliffordp** [comment]
dude, you're fast!

And if the plugin's strings are written in `en_US`, should I add "Language: en_US\n" as a property in the header?

**Comment by cliffordp** [comment]
you said leave blank, but WP CLI command produces this:
```
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
```

Should I leave that or pass `--headers` to override them to an empty string?

**Comment by swissspidy** [comment]
POT files have no Language header, but of course in the PO file you are generating you could add en_US there for a translation to English (US).

> Should I leave that

You can leave that. It's a reminder for people manually translating the files that those are placeholders. Software like POEdit would automatically replace it anyway.

**Comment by cliffordp** [comment]
And for plugins hosted at .org (I know I don't need to generate a .pot anyway but...) if the plugin is using their translation service, would this be the most correct heading entry (or still leave the placeholders)?:
"Last-Translator: WP-Translations <wpt@wp-translations.org>\n"
"Language-Team: WP-Translations <https://wp-translations.org/>\n"

**Comment by swissspidy** [comment]
https://wp-translations.org/ is not an official service affiliated with WordPress.org in any way, so: no 🙂 

I'd really just leave the placeholders

**Comment by cliffordp** [comment]
Many thanks to you!!!
