### ISSUE TITLE
make-pot: add support for JavaScript optional chaining operator

### ISSUE THREAD

**Issue by mloetsch** [wp-cli/i18n-command#218]
## Bug Report

**current  behavior**

the make-pot command seems to ignore javascript files using the optional chaining operator somewhere in the code completely.

**reproduction**

use the optional chaining operator in javascript files using the wp.i18n module like:
```
const {__} = wp.i18n;
..
..

const someReactComponent = () => (
 <>
   <a href={selectedPost?.link}>__('my translatable string')</a>
 </>
);
..
..
```

then use wp cli to generate a .pot file:

wp-cli wp i18n make-pot <plugin_dir> ./languages/<domain>.pot

**expected outcome**

the wp-cli i18n make-pot command includes javascript files using the optional chaining operator and successfully extracts the translation strings

**Comment by swissspidy** [comment]
Great timing, our upstream library that implements JS parsing just introduced support for this 3 days ago: https://github.com/mck89/peast/releases/tag/v1.10.4

Fixing this should be as easy as a version bump in `composer.json`

**Comment by swissspidy** [comment]
Closing for now since this was fixed upstream a long time ago.
