### ISSUE TITLE
JS extractor misses plural strings that use an expression (and not a variable) as their discriminator

### ISSUE THREAD

**Issue by davilera** [wp-cli/i18n-command#225]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Assuming a JavaScript file with the following content:

```js
_n( '%d var (_n)', '%d vars (_n)', x, 'domain' );
_n( '%d prop (_n)', '%d props (_n)', x.y, 'domain' );
_n( '%d function (_n)', '%d functions (_n)', Math.abs(x), 'domain' );
_n( '%d operation (_n)', '%d operations (_n)', x + x, 'domain' );

_nx( '%d var (_nx)', '%d vars (_nx)', x, 'context', 'domain' );
_nx( '%d prop (_nx)', '%d props (_nx)', x.y, 'context', 'domain' );
_nx( '%d function (_nx)', '%d functions (_nx)', Math.abs(x), 'context', 'domain' );
_nx( '%d operation (_nx)', '%d operations (_nx)', x + x, 'context', 'nelio-content' );
```

Running `wp i18n make-pot` should extract 8 plural strings. However, it only extracts 2:

```pot
#: script.js:1
msgid "%d var (_n)"
msgid_plural "%d vars (_n)"
msgstr[0] ""
msgstr[1] ""

#: script.js:6
msgctxt "context"
msgid "%d var (_nx)"
msgid_plural "%d vars (_nx)"
msgstr[0] ""
msgstr[1] ""
```

which makes me think `wp i18n make-pot` is unable to extract the strings if the third argument of `_n` or `_nx` is not a variable (`x`) but things like an object property (`x.y`), function calls (`Math.abs(x)`), or operations (`x + x`)

**Describe how other contributors can replicate this bug**

- Create a simple plugin and add a `script.js` file with the previous content
- Run `wp i18n make-pot` in the plugin
- The resulting `pot` file will not include all strings

**Describe what you would expect as the correct outcome**

The resulting `pot` file should contain all strings.

**Provide a possible solution**

When running the `make-pot` string with the _debug_ flag, I don't get any parsing issues. However, it looks like `make-pot` ignores `_n` and `_nx` calls if the third argument is not a _word_. I suppose it should also accept valid expressions...

**Comment by christiaanstijnen** [comment]
Hi, I just came across this ticket while noticing the same bug after debugging this for a while. Any chance on a fix for this?! Thanks!

**Comment by swissspidy** [comment]
Good news!

I just opened #258 to address this bug.
