### ISSUE TITLE
Report incorrect text domains

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/i18n-command#226]
## Feature Request

It would be great if wp i18n make-pot command would have a check for "incorrect" textdomains.
e.g. if "--domain=foo-bar" is specified, it should report all strings that have a different textdomain than "foo-bar" as error.

It happens regularly, that people missspell textdomains or accidentally use the textdomain of another plugin. A way to get notified about these would be nice.
Doesn't have to be automatic, a flag --report-other-domains=true would be perhaps even better.

**Comment by swissspidy** [comment]
Interesting suggestion! Should be trivial to implement.

We already report lots of useful messages  when using the `--debug` flag, so I think we could just extend that a bit.

**Comment by kkmuffme** [comment]
To add on to it bc I saw it in 2 plugins today: also report if the textdomain is empty alltogether, e.g. `esc_html_e( 'foo', '' );`

Potentially also for context, like:
`_x( 'foo', '', 'bar' )`
however in that case the error message should perhaps be: "Do not use _x with empty context. Use __() instead"

**Comment by swissspidy** [comment]
The one thing that comes to mind here is that projects can have multiple text domains, and someone you just want to scan 1 of them. Adding messages in that case would be very noisy and unwanted, so a separate flag might indeed be better.

> however in that case the error message should perhaps be: "Do not use _x with empty context. Use __() instead"

That is better suited for a linter like https://github.com/WordPress/wordpress-coding-standards :-)

**Comment by kkmuffme** [comment]
Yeah you are right, makes more sense to handle this wp phpcs standards only
