### ISSUE TITLE
Translators comment audit - tell me in which files the different comment is

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/i18n-command#227]
I have 1000s of files (from different projects that share a text-domain since its the same theme and texts just with slightly different design) with this string:
`'Hi %s'`

I get the following error:
Warning: The string "Hi %s," has 3 different translator comments. (some/file.php)

**Since wp-cli knows in which these different translator comments are, could you please also output this info to the user?**
Since I have about 7 of these warnings, it would take weeks to sift through all files and check where/what is different, since sometimes strings are on the same line, sometimes on the previous,...

**Comment by swissspidy** [comment]
Interesting suggestion!

> Since wp-cli knows in which these different translator comments are, could you please also output this info to the user?

I don't think it's as easy as that.

Warnings like that are printed once all the processing is done and all translations have been extracted.

For example:

If you have the same string used in 10 different files, but in one of the files it uses a different comment, we don't know which file that is.

We only know the 10 file names, and the list of comments, but not which comment belongs to which file.

> Since I have about 7 of these warnings, it would take weeks to sift through all files and check where/what is different, since sometimes strings are on the same line, sometimes on the previous,...

I don't think it takes that long :-)

Searching for a string in your IDE will quickly show an overview of all occurrences, and then you scan scan through the comments. And the POT file contains all file names too.

**Comment by kkmuffme** [comment]
>If you have the same string used in 10 different files, but in one of the files it uses a different comment, we don't know which file that is.

Ah ok, so the underlying tool doesnt report that - makes sense why you cannot report, which files are incorrect.

>We only know the 10 file names, and the list of comments, but not which comment belongs to which file.

That would actually be sufficient too! Just output the different translators comments, instead of just "3 different translator comments." This would make fixing these issues massively easier - talking from days to 10 minutes, since I can just search for the translators comment.
Would really appreciate if you could change this, as I guess it's just a small tweak to output the comments in the error message.

>I don't think it takes that long :-)
>Searching for a string in your IDE will quickly show an overview of all occurrences, and then you scan scan through the comments. And the POT file contains all file names too.

Unfortunately, it really does take ages. Since translators comments can be added in various ways (same line, previous line, phpdoc comment style, comment style,...) this means each and every string occurence has to be checked.
It takes about 10 seconds per string occurence in 1000s of file. This means each string error will roughly take 1 working day to fix (I've fixed one and that took me almost a day, then I started to just ignore the error for now)

**Comment by swissspidy** [comment]
In #318 I made the output as follows:

```
$ wp i18n make-pot foo-plugin
Plugin file detected.
Warning: The string "Hello World" has 2 different translator comments. (foo-plugin.php:7, foo-plugin.php:10)
translators: Translators 1!
Translators: Translators 2!
Success: POT file successfully generated!
```

**Comment by kkmuffme** [comment]
Thank you. Is this available in the latest nightly already?

**Comment by kkmuffme** [comment]
Doesn't work unfortunately. Tried `wp package install wp-cli/i18n-command` too, but neither works for me. I mean it installs fine, just the errors are still the same as before installation.

It shows up fine, but it doesn't work:

```
wp package list --allow-root
+---------------------+-----------------+----------+-----------+----------------+
| name                | authors         | version  | update    | update_version |
+---------------------+-----------------+----------+-----------+----------------+
| wp-cli/i18n-command | Pascal Birchler | dev-main | available | 2.x-dev        |
+---------------------+-----------------+----------+-----------+----------------+
```

I'm on `WP-CLI 2.7.0-alpha-dc3beef`
