### ISSUE TITLE
How to use with custom text function❓

### ISSUE THREAD

**Issue by deepnees** [wp-cli/i18n-command#229]
Is there any way to work with custom text domain like __my('Text', 'domain', 'key'). __my function is first checking the key from theme options. if there is any text shows that text, if not works with __() wp function. For this case I want to detect __my function texts and add to pot file.

Thanks

**Comment by swissspidy** [comment]
No, this is currently not possible, but might be a reasonable addition if you wanna make a contribution.

The main challenge is for users to be able to specify how `__my( 'Text', 'domain', 'key' )` should be interpreted. In your case, it could be treated like `__()` but with the third argument ignored. But what if someone uses `__my2( 'Text', 'something else', 'context', 'key' )`? This is where things get complicated.

**Comment by akbilisim** [comment]
I have simple frontend texts and option panel to edit them. I use only 3 arguments. I don't need a complicated configuration. I used gulp task before with https://github.com/wp-pot/gulp-wp-pot and it has gettextFunctions variable for this issue. But gulp-wp-pot limited me for something else.
Their configuration was similar to this;

`	gettextFunctions: [
		{
			name: "__my"
		},
		{
			name: "__myEcho"
		},
		{
			name: "__"
		},
		{
			name: "_e"
		},
	        {
			name: "_ex",
			context: 2
		},
		{
			name: "_n",
			plural: 2
		},
		{
			name: "_n_noop",
			plural: 2
		},
		{
			name: "_nx",
			plural: 2,
			context: 4
		},
		...
	]`

**Comment by deepnees** [comment]
I have simple frontend texts and option panel to edit them. I use only 3 arguments. I don't need a complicated configuration. I used gulp task before with https://github.com/wp-pot/gulp-wp-pot and it has gettextFunctions variable for this issue. But gulp-wp-pot limited me for something else.
Their configuration is similar to this;

`gettextFunctions: [ { name: "__my" }, { name: "__myEcho" }, { name: "__" }, { name: "_e" }, { name: "_ex", context: 2 }, { name: "_n", plural: 2 }, { name: "_n_noop", plural: 2 }, { name: "_nx", plural: 2, context: 4 }, ... ]`

**Comment by swissspidy** [comment]
Well, same thing. It's the kind of cconfiguration option we would need here as well.

**Comment by deepnees** [comment]
It would be great if there is a plan to add this. 👀

**Comment by schlessera** [comment]
@deepnees We're currently discussing this in Slack.

My current thoughts are that you should have a flag like this to make this work:
```
wp i18n make-pot --add-gettext-function=__my,__myEcho
```
This could then also be added to a per-project `wp-cli.yml` configuration file like so:
```
i18n make-pot:
  add-gettext-function: __my,__myEcho
```
With this, the functions would always be added by default when you run the command from within the folder that contains this configuration file.
How does that sound? Do you think this solves your issue? Do you think there would be a use case where you absolutely had to _remove_ an already defined function?

**Comment by deepnees** [comment]
Yes, It will solve my simple need. How about complicated usages mentioned by @swissspidy?

**Comment by deepnees** [comment]
Is there any progress on this? --add-gettext-function=__my,__myEcho is good start to support this idea.

**Comment by swissspidy** [comment]
We’re all volunteers here, so time is scarce. I currently don‘t have much time to work on this, but if you‘re up for submitting a pull request that would be more than welcome!

**Comment by deepnees** [comment]
Well, I'm a simple developer. I forked and made some workaround changes for my needs. https://github.com/deepnees/i18n-command/pull/1
I hope you support this more properly in the future.
