### ISSUE TITLE
PHP 8 compatibility: Peast dependency will need an update

### ISSUE THREAD

**Issue by jrfnl** [wp-cli/i18n-command#230]
For your information:

The `mck89/peast` dependency of this project has a known incompatibility with the upcoming PHP 8 release.

Seeing that this project uses that dependency, I've taken the liberty to submit a PR to fix it.

So, as part of your efforts to make the `i18n-command` code compatible with PHP 8, the Peast dependency will need to be updated.

The new minimum version should be the version in which my PR is merged (or higher if so desired).

Refs:
* https://github.com/mck89/peast/pull/23
* https://wiki.php.net/rfc/namespaced_names_as_token#backward_incompatible_changes

**Comment by swissspidy** [comment]
Thanks a lot for the heads up @jrfnl, really appreciate it!

I was planning on updating that dependenccy anyway (long overdue!), so I'll keep an eye out on that PR to make sure we update to whatever version includes that fix as soon as it's released.

**Comment by jrfnl** [comment]
@swissspidy FYI: I've opened a second PR in their repo to fix their testsuite so they can actually start testing against PHP 8.

See: https://github.com/mck89/peast/pull/24

**Comment by jrfnl** [comment]
FYI: both PRs have been merged and I've opened a third PR now so the package will be tested against PHP 7.4 + 8 (Travis). There's no new tagged release yet, but as soon as there is, the version constraint for the package can be updated.
