### ISSUE TITLE
make-pot could not parse js files with class field declarations

### ISSUE THREAD

**Issue by oolleegg55** [wp-cli/i18n-command#232]
It seems like make-pot doesn't recognize [Class field declarations for JavaScript](https://github.com/tc39/proposal-class-fields) syntax.
For example. Trying to parse this code:
```javascript
import React, { Component } from 'react';
import { __ } from '@wordpress/i18n';

class Search extends Component {
	handleFetchData = () => {
		console.log( 'do' );
	};

	render() {
		return (
			<div>{ __( 'Hello!' ) }</div>
		);
	}
}

export default Search;
```
gives this error:
`Debug: Could not parse file search.jsx: Unexpected: handleFetchData (line 5, column 1) `

If the code replaced with another syntax:
```javascript
import React, { Component } from 'react';
import { __ } from '@wordpress/i18n';

class Search extends Component {
	handleFetchData() {
		console.log( 'do' );
	};

	render() {
		return (
			<div>{ __( 'Hello!' ) }</div>
		);
	}
}

export default Search;
```
it is parsed correctly and gives a desirable result:

```
Debug: Parsing file search.jsx (0.089s)
Debug (make-pot): Extracted 1 string (.105s)
```

**Comment by swissspidy** [comment]
Thanks for your report

Another reason for the need to update the underlying library

**Comment by swissspidy** [comment]
Is this still an issue with WP-CLI nightly?

Peast seems to be parsing this now just fine. Support for class fields was added recently: https://github.com/mck89/peast/releases/tag/v1.13.0

**Comment by simonhammes** [comment]
> Is this still an issue with WP-CLI nightly?

I just tried this locally with WP-CLI nightly. It did not work.

I guess this happens because the latest nightly .phar is too old for the 1.13 release of Peast:
The latest nightly release is from May 19 (https://github.com/wp-cli/builds/tree/gh-pages/phar), while Peast 1.13 was released on May 22 (https://github.com/mck89/peast/releases/tag/v1.13.0).

**Comment by swissspidy** [comment]
Interesting, thanks a lot for testing!

@schlessera Any idea why the nightly is so outdated? And would releasing a new version of this command ensure that the latest version of the Peast dependency is included?

**Comment by schlessera** [comment]
I'll have to look at the nightlies to see why they weren't rebuilt again. Probably the GHA cron job that disabled itself again.

But regardless of that, the nightly would still not include a new version of Peast, as versions are locked in `wp-cli/wp-cli-bundle`.

**Comment by swissspidy** [comment]
Makes sense. Then I suppose releasing v2.2.9 of this command would help.

**Comment by swissspidy** [comment]
@simonhammes With 2.2.9 now out, does `wp package install wp-cli/i18n-command` / `wp package update` now resolve the issue?

**Comment by swissspidy** [comment]
Closing for now since all that's left to be done is doing some version bumps here and there.
