### ISSUE TITLE
make-pot fails with SIG 127, without any message.

### ISSUE THREAD

**Issue by tomalec** [wp-cli/i18n-command#233]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I encounter this issue while trying to build http://github.com/woocommerce/woocommerce. One of the build steps it to run 
```sh
$ wp --allow-root i18n make-pot . --exclude=\".github,.wordpress-org,bin,sample-data,node_modules,tests\" --slug=woocommerce
Plugin file detected.
 SIG(127) 
$
```
For some reason, it fails with signal 127 and produces no message to help to debug it.

**Describe how other contributors can replicate this bug**

1. `git clone git@github.com:woocommerce/woocommerce.git` (@2d6d53ed6fbfd97acbad2b1bdda9291e32367163 if that makes a difference)
2. `npm install && composer install`
3. `npm run build`

(Forgive me that it's not isolated, but I'm new to this codebase and trying to set it up for the first time ;) )

**Describe what you would expect as the correct outcome**

Preferably, work without any errors 😁 , but if there are any failures, I'd like to see the reason, error message, or hint what actually failed.

**Let us know what environment you are running this on**

```
OS:	Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/Applications/MAMP/bin/php/php7.4.9/bin/php
PHP version:	7.4.9
php.ini used:	/Applications/MAMP/bin/php/php7.4.9/conf/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/tomalec/repos/woo2
WP-CLI packages dir:	
WP-CLI global config:	/Users/tomalec/.wp-cli/config.yml
WP-CLI project config:	
WP-CLI version:	2.4.0

```

**Provide a possible solution**

🤷‍♂️

**Provide additional context/Screenshots**

I have a feeling that the failure may be related to the composer version:
```
$ composer diagnose

A script named bin would override a Composer command and has been skipped
Checking composer.json: WARNING
require.automattic/jetpack-autoloader : exact version constraints (2.2.0) should be avoided if the package follows semantic versioning
require.automattic/jetpack-constants : exact version constraints (1.5.0) should be avoided if the package follows semantic versioning
require.composer/installers : exact version constraints (1.7.0) should be avoided if the package follows semantic versioning
require.maxmind-db/reader : exact version constraints (1.6.0) should be avoided if the package follows semantic versioning
require.pelago/emogrifier : exact version constraints (3.1.0) should be avoided if the package follows semantic versioning
require.psr/container : exact version constraints (1.0.0) should be avoided if the package follows semantic versioning
require.woocommerce/action-scheduler : exact version constraints (3.1.6) should be avoided if the package follows semantic versioning
require.woocommerce/woocommerce-admin : exact version constraints (1.6.3) should be avoided if the package follows semantic versioning
require.woocommerce/woocommerce-blocks : exact version constraints (3.6.0) should be avoided if the package follows semantic versioning
require.league/container : exact version constraints (3.3.3) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.10.16 => 2.0.4)
Composer version: 1.10.16
PHP version: 7.1 - Package overridden via config.platform (actual: 7.4.9)
PHP binary path: /Applications/MAMP/bin/php/php7.4.9/bin/php
OpenSSL version: OpenSSL 1.0.2u  20 Dec 2019
```

**Comment by tomalec** [comment]
It turned out to be exceeded memory problem mentioned at https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment#install-dependencies-and-generate-assets

However, still, it would be nice to get an error message.

**Comment by swissspidy** [comment]
Just checked out the WooCommerce repo and ran `composer makepot`

```bash
$ composer makepot
A script named bin would override a Composer command and has been skipped
> wp --allow-root i18n make-pot . --exclude=".github,.wordpress-org,bin,sample-data,node_modules,tests" --slug=woocommerce '--skip-audit'
Plugin file detected.

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /Users/pascalb/Workspace/WordPress/woocommerce/bin/composer/wp/vendor/mck89/peast/lib/Peast/Syntax/LSM.php on line 131
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /Users/pascalb/Workspace/WordPress/woocommerce/bin/composer/wp/vendor/mck89/peast/lib/Peast/Syntax/LSM.php on line 131
Script wp --allow-root i18n make-pot . --exclude=".github,.wordpress-org,bin,sample-data,node_modules,tests" --slug=woocommerce handling the makepot-audit event returned with error code 255
Script @makepot-audit --skip-audit was called via makepot
```

Looks all correct to me.

**Comment by tomalec** [comment]
🤔  hm... 
Then what's wrong with my machine? (just tried bare bash, and have the same effect)

```shell
bash-3.2$ wp --allow-root i18n make-pot . --exclude=".github,.wordpress-org,bin,sample-data,node_modules,tests" --slug=woocommerce '--skip-audit'
Plugin file detected.
bash-3.2$ composer makepot
A script named bin would override a Composer command and has been skipped
> wp --allow-root i18n make-pot . --exclude=".github,.wordpress-org,bin,sample-data,node_modules,tests" --slug=woocommerce '--skip-audit'
Plugin file detected.
Script wp --allow-root i18n make-pot . --exclude=".github,.wordpress-org,bin,sample-data,node_modules,tests" --slug=woocommerce handling the makepot-audit event returned with error code 255
Script @makepot-audit --skip-audit was called via makepot
bash-3.2$ 
```

**Comment by swissspidy** [comment]
No idea 🤷  Perhaps error reporting/displaying disabled in the PHP config or something

**Comment by schlessera** [comment]
@tomalec Where did you get that "signal" output from? Is that a custom shell extension?

The 127 you are getting is not a signal, but the exit code of the WP-CLI command. The most likely scenario I can think of where you're getting a 127 exit code is when PHP tries to execute another binary via `exec()/system()/passthru()` but it doesn't find it or doesn't have access to it. As you seem to be running MAMP, chances are high that you're not running WP-CLI in a fully compliant POSIX environment, so that would be where I'd start the diagnosis.

**Comment by schlessera** [comment]
Also, as @swissspidy suggested, you might have disabled error reporting, so look into re-enabling that and/or check log files.

**Comment by tomalec** [comment]
Thanks a lot!
Yes, it was disabled `display_errors` in my PHP 🤦 

> Where did you get that "signal" output from? Is that a custom shell extension?

It's a custom oh-my-zsh, you're right it's exit code.
