### ISSUE TITLE
Prevent `wp i18n make-pot` from overwriting my translations.

### ISSUE THREAD

**Issue by raphaelparent** [wp-cli/i18n-command#234]
I have a workflow question.

So I have added all the string that need to be translated in my php and js (gutenberg) files. I then proceeded to create the `.pot` file using the command

```
wp i18n make-pot src languages/fr_FR.pot --domain=examples
```

I've noticed that if I rerun this command, after adding new strings to my code, it completely overwrites the translations I manually added in the `.pot` file. Does this mean I have to re-enter all of my translations? Is there a combinations of parameters made to update the file instead of overwriting it? I have looked at the documentation and the issues on this repo but I haven't found anything of interest.

Is there a better workflow? Am I missing something?

Thanks for the help!

**Comment by swissspidy** [comment]
The POT file is a catalogue of strings to be translated. It **must not** contain any actual translations. To add translations, copy the POT file and save it as a PO file for the respective language. So if your POT file is named `my-awesome-plugin.pot` and you want to add translations for fr_CA, save it as `my-awesome-plugin-fr_CA.po`, and add all the translations there.
