### ISSUE TITLE
make-pot not working with constants

### ISSUE THREAD

**Issue by GoddamnNoise** [wp-cli/i18n-command#236]
If a .php file contains a call to a translate function like __() and the string to translate or the text domain is a constant defined with the PHP function define(), the make-pot utility won't recognize the string and won't add it to the .pot file.

Example:

`define ('STRING_TO_TRANSLATE', 'string to translate');
...
__(STRING_TO_TRANSLATE); // The "string to translate" string won't be added to the .pot file`

**Comment by swissspidy** [comment]
String extraction does not execute your code. It will not know the value of the constant, it‘s simply not possible without running the code.
