### ISSUE TITLE
Add additional keyword

### ISSUE THREAD

**Issue by cyrilmarceau** [wp-cli/i18n-command#239]
Hello,

I want create a .pot but I have a problem. i have create a function _k() for translate my javascript files. How can I use it with wp-cli for generate my file.

Thanks,

**Comment by swissspidy** [comment]
Hi there,

This WP-CLI command only supports string extraction for the functions used by WordPress and the [`@wordpress/i18n`](https://www.npmjs.com/package/@wordpress/i18n) package, like `__()` or `_x()`. It does not support custom functions and there is no way to do so.

If you want to support any custom function, you would need to fork this repository to extend the configuration here:

https://github.com/wp-cli/i18n-command/blob/0fa24efa7460564d17fa4c6e1763e806eb1613c3/src/PhpCodeExtractor.php#L13-L43

With that being said: please note that GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review [http://wp-cli.org/#support](http://wp-cli.org/#support).

The easiest way to get support is to join us in the [`#cli`](https://wordpress.slack.com/messages/C02RP4T41) channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
