### ISSUE TITLE
Can I disable/remove paths comments?

### ISSUE THREAD

**Issue by fiullax** [wp-cli/i18n-command#240]
There's a way to disable/remove paths commets from the .pot file?? I didn't found a parameter or an issue about that.

```
#: admin/class-cnta-admin-page.php:11 <-- I want remove these 2 comments
#: includes/class-cnta-row-actions.php:135
msgid "Are you sure you want to do this?"
msgstr ""
```

**Comment by swissspidy** [comment]
There currently is no way to do that. Could you perhaps elaborate on why you‘d want to remove this standard and expected comment?

**Comment by fiullax** [comment]
Because I think these comments are annoying when I look to git diff, without it I can clearly see what strings are added or removed. This is my opinion, I was just curious if there was a way to do it.

**Comment by swissspidy** [comment]
I see. Well, looks like [xgettext](https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html) has a `--no-location` param for that, so we could add such a param here too.

Note that using this option makes it harder for technically skilled translators to understand each message’s context.

**Comment by fiullax** [comment]
Good! In my case remove this comments is not a problem, we have not enormous projects with many people at work.
Hope this parameter can be added!
