### ISSUE TITLE
Use Text Domain header from theme or plugin as default slug

### ISSUE THREAD

**Issue by roborourke** [wp-cli/i18n-command#244]
## Feature Request

 

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

I think given that the make-pot command detects and reads data from a plug-in or theme file it would make sense to use the specified text domain (if present) as the default domain and slug for generating the output file.

I think it would help with automation and make it easier for folks to create po and mo files with the correct names that WordPress can load automatically.

**Describe the solution you'd like**

I’m not totally sure if it has come up before - I couldn’t find anything while searching the issues on this repo at least but I think the following makes sense:

- if domain argument is unspecified use default value from main file if available 
- if slug is also unspecified use the text domain value from the main file

**Comment by swissspidy** [comment]
Isn‘t that already the case?

If the domain is set in the file header it takes precedence.

https://github.com/wp-cli/i18n-command/blob/606bbaba4471021f5404a8a78f495808c00535da/src/MakePotCommand.php#L307

**Comment by roborourke** [comment]
Ah missed that line, maybe I have an older version as that’s not what I observed yesterday. Thanks Pascal!
