### ISSUE TITLE
Command to add text domains to i18n functions

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/i18n-command#25]
It might be a good time to think about a `wp i18n add-text-domain` command.

See #7, #11 for discussions / some background about this.

**Comment by swissspidy** [comment]
This would mean we need to work with the AST of  PHP / JavaScript file.

https://github.com/wp-cli/i18n-command/pull/26 already uses a JS AST parser.

https://github.com/nikic/PHP-Parser is a popular one for PHP. It would make sense to use that for the `make-pot` task as well (less dependencies as https://github.com/oscarotero/Gettext wouldn't be needed anymore, improved code sharing), however it requires PHP 7.

**Comment by swissspidy** [comment]
After looking at #28 I think this command would need:

1. An `--only-missing` option to only add the domain where it's missing
2. A way to only replace a specific domain with a new one, in case the source folder contains strings with multiple text domains.

**Comment by varunsridharan** [comment]
@swissspidy is there any update on this ?

**Comment by varunsridharan** [comment]
@swissspidy how can i use `add-text-domain` cmd in cli to append text domains to wp functions inside my plugin / theme ( `__()` )

**Comment by swissspidy** [comment]
@varunsridharan No update I am afraid. `add-text-domain` does currently not exist.

However, you can achieve this using the [WordPress-Coding-Standards](https://github.com/WordPress/WordPress-Coding-Standards) PHPCS configuration as long as you [set your text domain accordingly](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#internationalization-setting-your-text-domain).

I think that is probably the best solution for this specific task.

Once you've configured PHPCS with the WordPress coding standards, you can use phpcbf to automatically fix any i18n functions that don't use your required text domain.

**Comment by varunsridharan** [comment]
@swissspidy thanks for your faster reply. well i work on quite a lot of projects and i use common rules-set.xl in phpstorm and i dont think that will work for me :-(

**Comment by swissspidy** [comment]
I think that should still work. You don't have to include all of WPCS in your ruleset, just the text domain sniff is enough. Then, you can even auto-fix things directly in PHPStorm.

**Comment by varunsridharan** [comment]
Based on my testing i can say that PHPStorm dose not support multiple ruleset in a single project.

**Comment by varunsridharan** [comment]
@swissspidy thanks for your time. i was not able to get this done using PHPStrom / Rule set not sure why may be i was doing something wrong.

and i created a simple composer package which dose this job
https://github.com/varunsridharan/wp-cli

**Comment by swissspidy** [comment]
Closing for now as this seems better suited for a tool like PHPCS, as mentioned in the discussion above. https://github.com/varunsridharan/wp-cli-textdomain exists for people who want a dedicated command/script.
