### ISSUE TITLE
Windows style newline used on linux

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/i18n-command#250]
## Bug Report

the .pot files have \r\n instead of \n line endings, even when running the make-pot command on linux.

This may lead to incompatibilites down the line and should be fixed.

**Comment by swissspidy** [comment]
Hi there,

I am unable to reproduce this. Can you perhaps share some more info?

Jus tested this in a plugin like so:


```bash
$ wp i18n make-pot . output.pot`
$ file -k output.pot
output.pot: GNU gettext message catalogue text, UTF-8 Unicode text
```

`cat -e output.pot` also shows `$` (`\n` aka `LF`) line endings.

Also, the relevant files would be:

https://github.com/wp-cli/i18n-command/blob/45c08a977db94991d69a9879d7a92cde67ea91e9/src/PotGenerator.php

https://github.com/php-gettext/Gettext/blob/v4.8.4/src/Generators/Po.php

https://github.com/php-gettext/Gettext/blob/v4.8.4/src/Generators/Generator.php

They all use `\n`, so I don't see where this would be happening.

**Comment by kkmuffme** [comment]
Hm strange, maybe I had some old pot file or an old version. Marking it as closed
