### ISSUE TITLE
make-pot doesn't extract strings from block.json files when --ignore-domain is used

### ISSUE THREAD

**Issue by dlind1** [wp-cli/i18n-command#252]
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [X] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Running `wp i18n make-pot <path to my-plugin> my-plugin.pot --slug=my-plugin --ignore-domain --skip-audit` results in no strings extracted from block.json files when the files contain non-empty `"textdomain"` property. This currently affects the translations for Gutenberg block names at https://translate.wordpress.org.

**Describe how other contributors can replicate this bug**

- Have a block.json available in an empty folder with the following contents:
```json
{
	"apiVersion": 2,
	"name": "core/archives",
	"title": "Archives",
	"category": "widgets",
	"description": "Display a monthly archive of your posts.",
	"textdomain": "gutenberg",
	"attributes": {
		"displayAsDropdown": {
			"type": "boolean",
			"default": false
		},
		"showPostCounts": {
			"type": "boolean",
			"default": false
		}
	},
	"supports": {
		"align": true,
		"html": false
	},
	"editorStyle": "wp-block-archives-editor"
}
```
- Run `wp i18n make-pot . test.pot --slug=test --ignore-domain --skip-audit`
- Confirm that test.pot contains no extracted strings

**Describe what you would expect as the correct outcome**

test.pot should've contained the strings extracted from block.json

**Let us know what environment you are running this on**

Can be reproduced locally and seems to be the case on translate.wordpress.org as well.

**Provide a possible solution**

Changing the logic to always extract strings if `--ignore-domain` option is used fixes it and can be done by changing the check in https://github.com/wp-cli/i18n-command/blob/master/src/BlockExtractor.php#L38 to `if ( null !== $translations->getDomain() && null !== $domain && $domain !== $translations->getDomain() )`.
I have the fix working locally with updated tests and can submit a PR.

**Comment by swissspidy** [comment]
Thanks for your report! Appreciate any PR!

The reason for translate.wordpress.org might be a different one, being tracked at https://meta.trac.wordpress.org/ticket/5737

**Comment by dlind1** [comment]
Thanks! I've created the [PR](https://github.com/wp-cli/i18n-command/pull/253).
With the issue on translate.wordpress.org, upgrading to the wp-cli version with the fix would be the easiest solution, otherwise it could be fixed by upgrading to a version with supports block.json extractions, removing all `"textdomain"` entries from block.json files and making a few other adjustments in the Gutenberg code to use the translations.
