### ISSUE TITLE
Strings from WordPress core's block-library.js are not extracted

### ISSUE THREAD

**Issue by ocean90** [wp-cli/i18n-command#255]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

First [reported on Slack here](https://wordpress.slack.com/archives/C02RP50LK/p1625399868111400). The [translation project for WordPress 5.8](https://translate.wordpress.org/locale/de/default/wp/dev/) is missing some strings, particularly from `block-library.js`.

**Describe how other contributors can replicate this bug**

- Download [block-library.js](https://github.com/WordPress/WordPress/blob/2f27f2419143f63cf67040511740c3c104094ad5/wp-includes/js/dist/block-library.js)
- Create a new folder with block-library.js
- cd into the new folder
- run `wp i18n make-pot . --ignore-domain` (or `php -d memory_limit=1G $(which wp) i18n make-pot . --ignore-domain` in case of memory limit issues)
- Open block-library.pot and notice that no strings are extracted

**Describe what you would expect as the correct outcome**

The resulting POT file should include "Text settings", "Toggle to show a large initial letter.", "Drop cap" any many more.

**Let us know what environment you are running this on**

```
❯ wp cli info
OS:	Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/local/Cellar/php@7.4/7.4.19_1/bin/php
PHP version:	7.4.19
php.ini used:	/usr/local/etc/php/7.4/php.ini
MySQL binary:	/usr/local/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.3.28-MariaDB, for osx10.16 (x86_64) using readline 5.1
SQL modes:
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/Dominik/Desktop/block-library
WP-CLI packages dir:	/Users/Dominik/.wp-cli/packages/
WP-CLI global config:	/Users/Dominik/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version:	2.5.0
```

**Provide additional context/Screenshots**

Might be related to WordPress now using modern JavaScript syntax for these files.

**Comment by swissspidy** [comment]
If you use the `—debug` flag, is there any warning about the file not being parseable?

**Comment by ocean90** [comment]
Yep!

```
Debug (make-pot): Parsing file block-library.js (0.103s)
Debug (make-pot): Could not parse file block-library.js: Unexpected: ( (line 28847, column 5) (2.469s)
Debug (make-pot): Extracted 0 strings (2.53s)
```


```js
const getTermsInfo = terms => ({
  terms,
  ...(terms === null || terms === void 0 ? void 0 : terms.reduce((accumulator, term) => { // This is line 28847
    const {
      mapById,
      mapByName,
      names
    } = accumulator;
    mapById[term.id] = term;
    mapByName[term.name] = term;
    names.push(term.name);
    return accumulator;
  }, {
    mapById: {},
    mapByName: {},
    names: []
  }))
});
```

**Comment by swissspidy** [comment]
Just did a quick test in Peast and it seems that the issue seems to be related to the parentheses around the object expression.

Oddly enough the following code seems to work:

```js
const getTermsInfo = terms => {
    return {
        terms,
        ...(terms === null || terms === void 0 ? void 0 : terms.reduce((accumulator, term) => { // This is line 28847
            const {
            mapById,
            mapByName,
            names
            } = accumulator;
            mapById[term.id] = term;
            mapByName[term.name] = term;
            names.push(term.name);
            return accumulator;
        }, {
            mapById: {},
            mapByName: {},
            names: []
        }))
    };
}
```

I filed a bug upstream: https://github.com/mck89/peast/issues/38

**Comment by gziolo** [comment]
As a quick fix can we split this very complex expression in smaller chunks, for example:
```js
const getTermsInfo = terms => {
    const rest = terms === null || ....;
    return {
        terms,
        ...rest
    };
}
```

**Comment by swissspidy** [comment]
@ocean90 With the underlying bug now fixed, you could update the Peast dependency in your fork of this package that you're using on dotorg.

I assume we'll update the dependency here once there's a new tagged release.

**Comment by ocean90** [comment]
> @ocean90 With the underlying bug now fixed, you could update the Peast dependency in your fork of this package that you're using on dotorg.

This was done in https://github.com/ocean90/wp-cli-bundle/commit/47e8927dd4eaf39fcc8400fa8e8ee38751984d6c and deployed to dotorg. The updated POT file does now include the missing block-library strings, see https://i18n.trac.wordpress.org/changeset/623359.

**Comment by swissspidy** [comment]
Awesome, closing this one for now then 👍
