### ISSUE TITLE
String wrapped in backquotes not extracted

### ISSUE THREAD

**Issue by vlad-timotei** [wp-cli/i18n-command#257]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**
First [reported here](https://github.com/WordPress/pattern-directory/issues/260), the translation project for Patterns has a [broken string](https://translate.wordpress.org/projects/meta/pattern-directory/ro/default/?filters%5Boriginal_id%5D=12101839) resulting from not extracting the string in backquotes, but the textdomain instead. 

[Source file](https://github.com/WordPress/pattern-directory/blob/841f5a9beb1106bd23a76a6cd0e313ccd07c2f56/public_html/wp-content/plugins/pattern-creator/src/plugins/viewport-header-control.js#L117):

```
text={ sprintf(
		/* translators: %s viewport width as css, ie: 100% */
		__( `Width (%spx)`, 'wporg-patterns' ),
		viewportWidth
) }
```

Output: 
```
#. translators: %s viewport width as css, ie: 100%
#: src/plugins/viewport-header-control.js:117
msgid "wporg-patterns"
msgstr ""
```

Mentioning @ocean90 as he can provide more info. 😃 Thank you!

**Comment by swissspidy** [comment]
Why are you using template literals instead of simple string literals (single/double quotes)? You're not using any expressions in there anyway.

Anyway, I just pushed #260 to fix this.

Just note that using expressions in template literals, e.g. something like

```js
`Width ${x} (%spx)`
```

would still not be supported, as this is not something that can be translated.

**Comment by vlad-timotei** [comment]
> Why are you using template literals instead of simple string literals (single/double quotes)? You're not using any expressions in there anyway.
I proposed [here] (https://github.com/WordPress/pattern-directory/issues/260) to change them to single quotes. I have no idea why the developer chose to use backquotes there. 😕 
Thanks for the patch.
