### ISSUE TITLE
Breaking change in gettext 4.8.5

### ISSUE THREAD

**Issue by theimbender** [wp-cli/i18n-command#269]
In v4.8.5 of gettext, [this change](https://github.com/php-gettext/Gettext/pull/271) was made to cache redundant translator comments, but this breaks [`MakePotCommand.php`](https://github.com/wp-cli/i18n-command/blob/master/src/MakePotCommand.php#L683) because `$comment` can now be an object and not a string, if a `translators:` comment is found.

Not sure if the maintainers of this project wanted to reach out to gettext in case this should be backed out in their patch releases, or if the logic here should be changed, or if you'd want to just set `4.8.4` instead of `^4.8` in i18n's `composer.json`

**Comment by swissspidy** [comment]
Thanks for opening this. As I am the one who added this change I realized the issue as well the other day. Will look into the different options.
