### ISSUE TITLE
`--include` flag does not work as expected

### ISSUE THREAD

**Issue by rufus87** [wp-cli/i18n-command#271]
## Bug Report

**Describe what you would expect as the correct outcome**

I use this command to generate pot file from my plugin specific files. 

`wp i18n make-pot ./ languages/myplugin.pot --include="a.php,assets,includes/a.php,includes/b.php"`

Unfortunately generated pot file includes everything translatable from all files in my plugin and not only from the mentioned files/folders

**Let us know what environment you are running this on**

```
OS:     Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64
Shell:  /usr/sbin/nologin
PHP binary:     /usr/local/bin/php
PHP version:    7.4.20
php.ini used:
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/html/wp-content/plugins/woocommerce-gutenberg-products-block-fork
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.5.0
```

**Comment by swissspidy** [comment]
Thanks for your report

We've made some changes to `--include` recently that haven't been released yet.

Does this still happen when using the latest development version of this package? Install using:

```bash
wp package install git@github.com:wp-cli/i18n-command.git
```

**Comment by rufus87** [comment]
Many thanks for you quick response.

I've updated as you suggested. Nevertheless, `--include` flag does not work.

**Comment by swissspidy** [comment]
Can you share the output of the command when running with `--debug`? Thanks in advance.

**Comment by rufus87** [comment]
Here are some screenshots that will be helpful:

This is what I've run to generate .pot file.
![image](https://user-images.githubusercontent.com/10531492/126170695-753d73ac-be0a-462d-b5fe-9829f8c3e92c.png)

As you can see it worked. But the content it generate contains translatable strings from other files too, which are not indicated as value for `--include` parameter

![image](https://user-images.githubusercontent.com/10531492/126171112-75f62eb0-8e41-4e83-b708-81a7922d7548.png)

php files contents look like following:
![image](https://user-images.githubusercontent.com/10531492/126171235-1f4698f7-37c3-4f87-907a-4b34433929a4.png)
![image](https://user-images.githubusercontent.com/10531492/126171277-0c2a91af-e906-4214-9bdb-32323d75855a.png)
![image](https://user-images.githubusercontent.com/10531492/126171303-0d624430-9ac9-4765-8329-f02ad44e1097.png)

This is just a test plugin to play with.

Thanks

**Comment by rufus87** [comment]
And here is screenshot with `--debug` flag: (only .pot generating part)

![image](https://user-images.githubusercontent.com/10531492/126171597-a0b457f8-6faa-45bd-96ef-1e8e169fff7d.png)

**Comment by swissspidy** [comment]
Does this still happen after running `wp package install wp-cli/i18n-command` && `wp package update`?

**Comment by rufus87** [comment]
@swissspidy after running mentioned commands `wp package install wp-cli/i18n-command` & `wp package update` this issue still presents. Nothing's changed.

**Comment by swissspidy** [comment]
Just tested this locally with the current development version and got the expected output:

```
Debug (make-pot): Plugin file: /Users/pascalb/Workspace/WordPress/wp-cli-dev/i18n-command/tests/data/test-271/test-plugin.php (0.029s)
Debug (make-pot): Extracting all strings with text domain "test-plugin" (0.029s)
Debug (make-pot): Destination: /Users/pascalb/Workspace/WordPress/wp-cli-dev/i18n-command/tests/data/test-271/languages/test-271.pot (0.029s)
Debug (make-pot): Only including the following files: src/file2.php (0.029s)
Debug (make-pot): Excluding the following files: node_modules,.git,.svn,.CVS,.hg,vendor,Gruntfile.js,webpack.config.js,*.min.js (0.029s)
Debug (make-pot): Parsing file src/file2.php (0.032s)
Debug (make-pot): Extracted 2 strings (0.035s)
```

`file1.php` and `file3.php` were excluded.

So this will be fixed in the next proper release / nightly

**Comment by rufus87** [comment]
Thank you very much
