### ISSUE TITLE
Issue with POT file generation on certain JavaScript file

### ISSUE THREAD

**Issue by rufus87** [wp-cli/i18n-command#274]
## Bug Report

**Describe the current, buggy behavior**

To generate a pot file for a custom plugin, it is recommended to use following command within my plugin folder.

`wp i18n make-pot . myplugin.pot` 

As soon as plugin contains any minified JS file, the command fails with following message: `Uncaught Error in exception handling during call to Error::__tostring() in phar:///bin/wp-cli.phar/vendor/mck89/peast/lib/Peast/Syntax/Scanner.php on line 0`

**Describe how other contributors can replicate this bug**

- run `wp i18n make-pot . myplugin.pot` CLI command in any folder which contains any minified JS file.

**Let us know what environment you are running this on**

```
OS:     Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64
Shell:  /usr/sbin/nologin
PHP binary:     /usr/local/bin/php
PHP version:    7.4.20
php.ini used:
MySQL binary:
MySQL version:
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/html/wp-content/plugins/test-plugin
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.5.0
```

**Comment by swissspidy** [comment]
Thanks for your report.

Can you share the JS file which causes this issue?

We've been working a lot on this command lately, so it's possible that we've already fixed this.

But I can only confirm that if I have the offending JS to test.

**Comment by swissspidy** [comment]
Please also try `wp package install wp-cli/i18n-command` to see if this still happens for you now that v2.2.9 of this command is out.

**Comment by rufus87** [comment]
@swissspidy `wp package install wp-cli/i18n-command` command did not help at all. The issue's still there.

Please also see attached a generated JS file, which triggers the issue. (its in the zip, 'cause it's not allowed to attach .js files here)
[active-filters-frontend.zip](https://github.com/wp-cli/i18n-command/files/6853411/active-filters-frontend.zip)

**Comment by swissspidy** [comment]
Thanks for the JS file!

I've confirmed the issue is with this particular line in there:

```js
throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")
```

Reported upstream: https://github.com/mck89/peast/issues/41

**Comment by swissspidy** [comment]
Looks like false alarm.

I successfully parsed the whole `active-filters-frontend.js` just fine in the current version of Peast.

So this should work normally in the next release of this command / WP-CLI.

**Comment by rufus87** [comment]
Many thanks. Do you have a chance to check it myself now without waiting for the next release?

**Comment by swissspidy** [comment]
`wp cli update --nightly` and `wp package update` might help I think
