### ISSUE TITLE
Feature Request: equivalent command for msgmerge

### ISSUE THREAD

**Issue by EvanShaw** [wp-cli/i18n-command#278]
## Feature Request

**Describe your use case and the problem you are facing**

As far as I know, `wp-cli i18n` doesn't provide an equivalent for gettext's `msgmerge` command. This command is really useful for updating existing `po` files by merging a `pot` template created with `make-pot`. So, for example, if I add a new `__` call in my plugin like this:
```php
$newtranslation = __('Translate me please', 'domain');
```
I can update the `messages.pot` file with `make-pot`, but I have to update existing `po` files with the new translation by hand.

**Describe the solution you'd like**

To get around this, I've been calling `msgmerge` directly to update my `po` files:
```sh
find ./languages -name "*.po" | xargs -I % msgmerge -o % % languages/messages.pot
```
This merges the new translations of `messages.pot` into all existing `po` files in the `languages` directory. It would be great if the `i18n` command had a similar `update-pos` or `merge-pot` command to accomplish the same thing.

**Comment by swissspidy** [comment]
Thanks for opening this! Interesting request.

`msgmerge` documentation for reference: https://www.gnu.org/software/gettext/manual/html_node/msgmerge-Invocation.html

Related: the `make-pot` command has `--merge` and `--subtract-and-merge` flags.

**Comment by strarsis** [comment]
@swissspidy: Update `PO` files from `POT` file `npm` script ([used in Sage themes](https://discourse.roots.io/t/pot-generation-missing-options/14381/6?u=strarsis)):
```json
"translate:update": "for filename in ./resources/lang/*.po; do msgmerge -U $filename ./resources/lang/sage.pot; done; rm -f ./resources/lang/*.po~",
````
That script will automatically update all `PO` files from a `POT` file.

**Comment by swissspidy** [comment]
Yeah that works great. The idea here is to provide an msgmerge WP-CLI command so that you don‘t have to install msgmerge itself.

**Comment by strarsis** [comment]
The tests in `php-gettext` (`4.x`) [contains some examples that already come very close](https://github.com/php-gettext/Gettext/blob/4.x/tests/MergeTranslationsTest.php).

**Comment by swissspidy** [comment]
#316 implements this, in case you wanna give it a try.

Checking out that PR locally or using `wp package install wp-cli/i18n-command:dev-try/278-msgmerge` should work
