### ISSUE TITLE
Files with React's fragment short syntax are not being parsed

### ISSUE THREAD

**Issue by fluiddot** [wp-cli/i18n-command#281]
## Description

I noticed that when using [the short syntax of React's fragment](https://reactjs.org/docs/fragments.html#short-syntax) in a file, it's not being properly parsed by the command, it fails with the following error:

```
Could not parse file <FILE_NAME>: Unexpected: > (line 8, column 5)
```

**NOTE:** Using [the regular syntax `<React.Fragment></React.Fragment>`](https://reactjs.org/docs/fragments.html#usage) doesn't produce this issue.

## How to reproduce it

1. Create an example JSX file with the following content and locate it in a folder (in this example I named the file `example.js` and the folder `/example`):
```
import React from 'react';
import { __ } from '@wordpress/i18n';

export default class Example extends React.Component {
	render() {
		return (
			<div className="example">
				<>
					<button onClick={ () => {} }>
						{ __( 'This is another button' ) }
					</button>
				</>
				<button onClick={ () => {} }>
					{ __( 'This is a button' ) }
				</button>
			</div>
		);
	}
}

```

**NOTE:** As far as I checked, it doesn't fail if the fragment is placed at the root of the JSX, but always fails if it's nested. The following code succeeds:

```
import React from 'react';
import { __ } from '@wordpress/i18n';

export default class Example extends React.Component {
	render() {
		return (
			<>
				<div className="example">
					<button onClick={ () => {} }>
						{ __( 'This is another button' ) }
					</button>
					<button onClick={ () => {} }>
						{ __( 'This is a button' ) }
					</button>
				</div>
			</>
		);
	}
}


```

2. Run command `wp i18n make-pot example --ignore-domain --debug example.pot`.
3. Observe that the command logs the error `Could not parse file` when parsing the file.
4. Observe that the POT file doesn't contain the `This is a button` and `This is another button` strings.

## Expected result

Files that contain React's fragment short syntax should be properly parsed.

In the previous example, the expected result in the POT file would be:
```
#: example.js:10
msgid "This is another button"
msgstr ""

#: example.js:14
msgid "This is a button"
msgstr ""
```

## Environment
- PHP version:	7.3.11
- WP-CLI 2.5.0

**Comment by swissspidy** [comment]
Verified and reported upstream: https://github.com/mck89/peast/issues/43

**Comment by swissspidy** [comment]
This was now fixed upstream.

It will be resolved in WP-CLI with the next dependency updates.
