### ISSUE TITLE
Consecutive comments => String extraction fail in the js file

### ISSUE THREAD

**Issue by cloudinstone** [wp-cli/i18n-command#285]
If there are more than two consecutive comments in js file, it will cause the string extraction in the file to fail.

for example: 

```
const a ="A"
{/* const b = "B"; */}
{/* const c = "C"; */}
const d = "D";
```

**Comment by simonhammes** [comment]
@cloudinstone I can't reproduce this locally (using `wp i18n make-pot .`).

Which version of WP-CLI are you running? (`wp cli info`)
And which command are you running with which args?
