### ISSUE TITLE
Use i18n schema for block.json from WordPress Core

### ISSUE THREAD

**Issue by gziolo** [wp-cli/i18n-command#287]
## Feature Request

 

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

`BlockExtractor` is using a hardcoded list of fields to translate from `block.json` file:

https://github.com/wp-cli/i18n-command/blob/ea8a6b3ab19c490798b420beabf06ece40b8e708/src/BlockExtractor.php#L46-L66

**Describe the solution you'd like**

Replicate the approach used for `ThemeJsonExtractor` that uses schema for `theme.json` located in WordPress core codebsase:

https://github.com/wp-cli/i18n-command/blob/ea8a6b3ab19c490798b420beabf06ece40b8e708/src/ThemeJsonExtractor.php#L106-L125

The schema for `block.json` is located at https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/block-i18n.json.

**Comment by swissspidy** [comment]
Related question:

Since https://schemas.wp.org/trunk/theme.json is now a thing apparently, any plans on making the the i18n schemas available there as well?

**Comment by gziolo** [comment]
Sure. It uses similar URL now:

https://schemas.wp.org/trunk/block.json

**Comment by swissspidy** [comment]
Who could set up these URLs?

**Comment by gziolo** [comment]
> Who could set up these URLs?

I see the URL got updated by @mkaz in https://github.com/WordPress/gutenberg/pull/36316, but I don't know who set them up. I can't see any reference in Meta WordPress Trac, too.

**Comment by mkaz** [comment]
@gziolo @swissspidy You can make the request on Systems blog.

Here's the requests I made for the schemas:
https://make.wordpress.org/systems/2021/11/03/redirects-for-json-schemas/

💛
