### ISSUE TITLE
Extract translatable string from any JSON-Files

### ISSUE THREAD

**Issue by leutrimhusaj** [wp-cli/i18n-command#288]
In some case there are several JSON-Files in a project where translatable String can be part of.
These strings should be included by the wp-cli parser and added to the generated po(t)/json files.

As the block.json Files can be parsed by the [BlockExtractor.php,](https://github.com/wp-cli/i18n-command/blob/master/src/BlockExtractor.php) is it possible to whether extend the BlockExtractor for other JSON-Files too or add a new JsonExtractor that parses all other JSON-Files for a list of attributes given by parameter.

**Comment by swissspidy** [comment]
What's your use case for this?

How would you load the translations in WordPress?

How would the extractor know which fields in your JSON file are translatable and which ones aren't?

You might want to consider forking/extending this command to add any custom extractor tailored to your needs.

**Comment by swissspidy** [comment]
Closing this for now for the reasons stated above
