### ISSUE TITLE
Strings from WordPress core's components.js are not extracted

### ISSUE THREAD

**Issue by ocean90** [wp-cli/i18n-command#297]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

The [translation project for WordPress 5.9](https://translate.wordpress.org/locale/de/default/wp/dev/) is missing some strings, particularly from [`components.js`](https://translate.wordpress.org/projects/wp/dev/de/default/?filters%5Bterm%5D=components.js).

**Describe how other contributors can replicate this bug**

- Download [components.js](https://github.com/WordPress/WordPress/blob/28a12c8bcefecb2a4b040f63c9ce6574abf473eb/wp-includes/js/dist/components.js)
- Create a new folder with components.js
- cd into the new folder
- run `wp i18n make-pot . --ignore-domain` (or `php -d memory_limit=1G $(which wp) i18n make-pot . --ignore-domain` in case of memory limit issues)
- Open the POT file and notice that no strings are extracted

**Describe what you would expect as the correct outcome**

The resulting POT file should include all strings from components.js.

**Let us know what environment you are running this on**

```
❯ wp cli info
OS:	Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/local/opt/php@7.4/bin/php
PHP version:	7.4.27
php.ini used:	/usr/local/etc/php/7.4/php.ini
MySQL binary:	/usr/local/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.3.32-MariaDB, for osx10.17 (x86_64) using readline 5.1
SQL modes:
WP-CLI root dir:	/Users/Dominik/Development/git/wp-cli
WP-CLI vendor dir:	/Users/Dominik/Development/git/wp-cli/vendor
WP_CLI phar path:
WP-CLI packages dir:	/Users/Dominik/Development/git/wp-cli/packages/
WP-CLI global config:	/Users/Dominik/.wp-cli/config.yml
WP-CLI project config:
WP-CLI version:	2.5.1-alpha
```

**Provide additional context/Screenshots**

The debug message:

> Debug (make-pot): Could not parse file components.js: Unexpected: 05 (line 38659, column 2225) (3.207s)

<img width="1088" alt="js-source" src="https://user-images.githubusercontent.com/617637/148119458-8bb417a7-6553-42bc-9c06-7ac13b2da0c0.png">

The source of this seems to be https://github.com/omgovich/react-colorful/blob/8681e3cbf6c7ca0c8ef3861a3c68d1a0ef1161fb/src/components/common/Interactive.tsx#L122-L123.

Might be a similar issue as in #255 and requires an upstream fix.

**Comment by swissspidy** [comment]
I was just about to open an issue on the Peast repo, but you beat me to it :-)

Not sure what would be a good workaround for the meantime. Maybe some build config to retain the leading zeros?

**Comment by swissspidy** [comment]
Now that the upstream bug has been fixed, I think all that‘s needed is updating the dependency here / in the final bundle

**Comment by wojsmol** [comment]
@swissspidy For now there is not release of Peast with this fix.

**Comment by wojsmol** [comment]
@swissspidy Peast library was updated to version with fixes for this issue in https://github.com/wp-cli/i18n-command/pull/299.
