### ISSUE TITLE
i18n without possible database connection

### ISSUE THREAD

**Issue by dtrunk90** [wp-cli/i18n-command#325]
Related to wp-cli/wp-cli#787 it's not possible to run make-json, make-mo or make-pot w/o a working db connection. It doesn't make sense to me as this commands should only parse files and create other files. There's no need for a working db connection.

**Comment by schlessera** [comment]
@dtrunk90 From what I'm seeing, these commands do not require a working DB connection. Can you elaborate on how you are trying to execute them when they are failing?
