### ISSUE TITLE
make-pot failing to parse specific JavaScript code

### ISSUE THREAD

**Issue by markhowellsmead** [wp-cli/i18n-command#347]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When running `wp i18n make-pot . languages/shp_gantrisch_adb.pot` on the command line in a site shell from the Local app on Mac OSX, a very long error message is generated. The initial message is `Warning: Uncaught Error in exception handling during call to Error::__toString() in phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar/vendor/mck89/peast/lib/Peast/Syntax/Scanner.php on line 0`

**Describe how other contributors can replicate this bug**
Run  `wp i18n make-pot . languages/shp_gantrisch_adb.pot` on the command line in a site shell from the Local app on Mac OSX.

**Describe what you would expect as the correct outcome**

The POT file be generated without any error messages.

**Let us know what environment you are running this on**

```
OS:	Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/Users/mark/Library/Application Support/Local/lightning-services/php-8.0.22+5/bin/darwin/bin/php
PHP version:	8.0.22
php.ini used:	/Users/mark/Library/Application Support/Local/run/_qwoyVNya/conf/php/php.ini
MySQL binary:	/Applications/Local.app/Contents/Resources/extraResources/lightning-services/mysql-8.0.16+6/bin/darwin/bin/mysql
MySQL version:	mysql  Ver 8.0.16 for macos10.14 on x86_64 (MySQL Community Server - GPL)
SQL modes:	ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/mark/Projects/fse/app/public/wp-content/plugins/shp_gantrisch_adb
WP-CLI packages dir:	
WP-CLI global config:	/Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/config.yaml
WP-CLI project config:	
WP-CLI version:	2.6.0
```

**Comment by swissspidy** [comment]
The environment does not seem relevant here. Typically an error with the Peast scanner indicates an issue with parsing JavaScript files, for which we'd have to file an issue upstream in the Peast repository.

Does the error still occur when you run `wp i18n make-pot . languages/shp_gantrisch_adb.pot --skip-js`? If not, then you'll need to find the offending JS file / function and ideally share it here for further debugging.

**Comment by markhowellsmead** [comment]
Thanks for the swift response @swissspidy. Excluding JS files stops the error from occurring. I'll look into that further.

**Comment by markhowellsmead** [comment]
I've tracked it down in one project to a piece of code where I'm using `useState` from the `@wordpress/elements` package. (The code is compiled to JS using [this Webpack task](https://github.com/SayHelloGmbH/hello-fse/blob/main/.build/gulp/task-gutenberg.js).)

```
const [processing, setProcessing] = useState(null);

…Various code…

if(condition){
    setProcessing(true);
}

```

If I comment out this single instance of `setProcessing(true);` and recompile my JS, then the POT can be created. If not, then it throws the long error message.

**Comment by swissspidy** [comment]
Cool, then I recommend opening an issue at https://github.com/mck89/peast with this minimal code to reproduce so that it can be fuxed there.

**Comment by markhowellsmead** [comment]
Response is that they can't help with the bug. See https://github.com/mck89/peast/issues/54#issuecomment-1342648900.
