### ISSUE TITLE
Translator comments are not extracted if they are not directly followed by a gettext function

### ISSUE THREAD

**Issue by ocean90** [wp-cli/i18n-command#4]
Example plugin file:

```php
<?php
/**
 * Plugin Name: Plugin name
 */

/* translators: TRANSLATORS!! */
_e( 'hello world', 'test-plugin' );

/* translators: TRANSLATORS!! */
$foo = __( 'foo', 'test-plugin' );
```

Running the makpot command creates this POT file:

```pot
# Copyright (C) 2017 Plugin name
# This file is distributed under the same license as the Plugin name package.
msgid ""
msgstr ""
"Project-Id-Version: Plugin name\n"
"Report-Msgid-Bugs-To: https://wordpress.org/support/plugin/test-plugin\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"POT-Creation-Date: 2017-12-13T17:11:07+00:00\n"
"PO-Revision-Date: 2017-12-13T17:11:07+00:00\n"
"X-Domain: test-plugin\n"

#. translators: TRANSLATORS!!
#: test-plugin.php:7
msgid "hello world"
msgstr ""

#: test-plugin.php:10
msgid "foo"
msgstr ""

#. Plugin Name of the plugin/theme
msgid "Plugin name"
msgstr ""
```

Note the missing comment for "foo".

**Comment by swissspidy** [comment]
I'll try to investigate this a bit.

Perhaps this needs to be reported upstream?

See https://github.com/oscarotero/Gettext/issues/100 and https://github.com/oscarotero/Gettext/pull/102.

**Comment by swissspidy** [comment]
Here's the gettext spec, for reference: https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/xgettext-Invocation.html#Operation-mode

It mentions a case like

```php
/* translators: this comment is ignored */
__(
    'foo',
    'test-plugin'
);
```

but not

```php
/* translators: TRANSLATORS!! */
$foo = __( 'foo', 'test-plugin' );
```

**Comment by swissspidy** [comment]
Okay so `xgettext --add-comments=translators --keyword=__:1 --add-location test.php` extracts that comment, but that library not.

**Comment by swissspidy** [comment]
This specific case is now addressed. https://github.com/oscarotero/Gettext/pull/166 now aims to improve support for multi-line comments and comments on the same line as the function.

I'll continue to address this in #23.
