### ISSUE TITLE
Require database when you run i18n

### ISSUE THREAD

**Issue by Mte90** [wp-cli/i18n-command#40]
I was trying the package on my host where I have VVV as VM, so is not easy to share the same database.
When I execute `wp i18n` alert me that the mysql connection didn't worked.

If I execute `make-pot` instead this error doesn't appear and I can use it without problems.
I am not sure if this behaviour on first level command require a db connection and the others can ignore that but just to let know about this error.

**Comment by schlessera** [comment]
Oh, nevermind, I misread the original issue. So this is only about getting the help to properly display when ihtting the parent command. Namespace it is, then.

**Comment by Mte90** [comment]
Yes as usual my english is so horrible that need another explanation XD

**Comment by schlessera** [comment]
@Mte90 Don't worry, it was my reading that was at fault here, not your writing.
