### ISSUE TITLE
make-pot not working for my project

### ISSUE THREAD

**Issue by SamirDeveloper** [wp-cli/i18n-command#403]
So actually I used WP CLI to create the POT file to translate a plugin,

I tried to used wp-cli, it worked at some point, I get the message "POT file succesfully generated" but the create POT file doesn't contain the file that I wanted to translate, which is called tdn.php,

This tdn.php file is situated in this path : 
`C:/wamp64/PathToPluginsRepo/plugins/NameOfThePlugin/lang/tdn.php`

Here's the line command I used to create the POT file : (I positioned myself in the wp-cli repository first) : 

`php wp-cli.phar i18n make-pot ../wamp64/PathToPluginsRepo/plugins/NameOfThePlugin/lang potfile.pot --include=-*tdn`

NOTE : 
I installed WP CLI on my laptop (windows), I've put it in this path C:/wp-cli/wp-cli.phar. 
I downloaded the WP CLI here : [https://make.wordpress.org/cli/handbook/guides/installing/](url) .
I have Wamp on my laptop too (C:/wamp64).

What can be the issue guys ? why the translation is not working well ? 

Thanks in advance !

**Comment by swissspidy** [comment]
- Make sure to use the `--debug` flag to see valuable debug information
	- You can see whether the file is being parsed or not. If not, try removing `--include` for example
	- You can see which text domain the script is looking for
- Verify that the `tdn.php` file contains valid gettext calls with the correct text domain
- If you're still stuck, follow the steps below and ideally share a GitHub repository with a repro case

----

Kind reminder:

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review [http://wp-cli.org/#support](http://wp-cli.org/#support).

The easiest way to get support is to join us in the [`#cli`](https://wordpress.slack.com/messages/C02RP4T41) channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by SamirDeveloper** [comment]
Thanks,
that's the result I find inside the potfile.pot after writing the code line mentioned in the first message : 
`msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"POT-Creation-Date: 2024-05-22T20:38:52+00:00\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"X-Generator: WP-CLI 2.10.0\n"
"X-Domain: lang\n"`

I tried the `php wp-cli.phar --debug` code line, but I got a lot of result lines, and I didn't understand anything in it

**Comment by swissspidy** [comment]
> I tried the php wp-cli.phar --debug code line, but I got a lot of result lines, and I didn't understand anything in it

Please share them all here.

Unfortunately that's not really helpful for debugging this.

- What is the exact name of your plugin
- What's the folder name
- What's the text domain in the main plugin header
- What's the contents of the `tdn.php` file

Again: ideally share a GitHub repository with a repro case

**Comment by SamirDeveloper** [comment]
Okey, sorry, here's the content asked for : 
Plugin Name : pluginName (let's assume)
Folder Name : pluginName (same as the plugin name)
Text Domain Name : pluginName (same as the plugin name)
tdn.php file : I generated this file using this line command : `php add-textdomain.php pluginName ../view/admn-view.php > tdn.php` , I used this command line in order to generate tdn.php file, and this command line adds the Text Domain Name at each end of Gettext function in the admn-view.php file (which is the original version of tdn.php but without Text Domain Name in its Gettext functions). and last comment, tdn.php file was generated very well, I've checked it, no errors, and all my printf() esc_html_e() functions are written well, and well coded.

By the way, I succeeded in generating the POT file one time, it generated everything I wanted to translate, but now, it just doesn't work, I don't know what's the reason why.

Here's what --debug parameter giving to me : 
`$ php wp-cli.phar --debug

Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\DeclareAbstractBa
seCommand (0.028s)
Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\IncludeFrameworkA
utoloader (0.029s)
Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\ConfigureRunner (
0.029s)
Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\IncludeRequestsAu
toloader (0.03s)
Debug (bootstrap): Setting RequestsLibrary::$version to v2 (0.03s)
Debug (bootstrap): Setting RequestsLibrary::$source to wp-cli (0.03s)
Debug (bootstrap): Setting RequestsLibrary::$class_name to \WpOrg\Requests\Reque
sts (0.031s)
Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\InitializeColoriz
ation (0.031s)
Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\InitializeLogger
(0.032s)
Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\DefineProtectedCo
mmands (0.032s)
Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\LoadExecCommand (
0.033s)
Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\LoadRequiredComma
nd (0.034s)
Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\IncludePackageAut
oloader (0.035s)
Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\IncludeFallbackAu
toloader (0.036s)
Debug (bootstrap): Fallback autoloader paths: phar://wp-cli.phar/vendor/autoload
.php (0.037s)
Debug (bootstrap): Loading detected autoloader: phar://wp-cli.phar/vendor/autolo
ad.php (0.044s)
Debug (bootstrap): Attaching command 'config edit' to hook before_wp_load (0.067
s)
Debug (bootstrap): Attaching command 'config path' to hook before_wp_load (0.068
s)
Debug (bootstrap): Attaching command 'config list' to hook before_wp_load (0.072
s)
Debug (bootstrap): Attaching command 'config get' to hook before_wp_load (0.073s
)
Debug (bootstrap): Attaching command 'config is-true' to hook before_wp_load (0.
073s)
Debug (bootstrap): Attaching command 'config set' to hook before_wp_load (0.074s
)
Debug (bootstrap): Attaching command 'config delete' to hook before_wp_load (0.0
75s)
Debug (bootstrap): Attaching command 'config has' to hook before_wp_load (0.076s
)
Debug (bootstrap): Attaching command 'config shuffle-salts' to hook before_wp_lo
ad (0.077s)
Debug (commands): Adding command: config (0.079s)
Debug (bootstrap): Attaching command 'core download' to hook before_wp_load (0.0
86s)
Debug (bootstrap): Attaching command 'core version' to hook before_wp_load (0.08
8s)
Debug (commands): Adding command: core (0.089s)
Debug (bootstrap): Attaching command 'eval' to hook before_wp_load (0.09s)
Debug (commands): Adding command: eval (0.091s)
Debug (bootstrap): Attaching command 'eval-file' to hook before_wp_load (0.092s)
Debug (commands): Adding command: eval-file (0.093s)
Debug (commands): Adding command: cache (0.096s)
Debug (commands): Adding command: transient (0.098s)
Debug (bootstrap): Attaching command 'core verify-checksums' to hook before_wp_l
oad (0.101s)
Debug (commands): Adding command: verify-checksums in core Namespace (0.101s)
Debug (commands): Adding command: plugin (0.102s)
Debug (commands): Adding command: verify-checksums in plugin Namespace (0.104s)
Debug (commands): Adding command: cron (0.105s)
Debug (commands): Adding command: event in cron Namespace (0.109s)
Debug (commands): Adding command: schedule in cron Namespace (0.111s)
Debug (bootstrap): Attaching command 'db' to hook after_wp_config_load (0.116s)
Debug (bootstrap): Attaching command 'db clean' to hook after_wp_load (0.117s)
Debug (bootstrap): Attaching command 'db tables' to hook after_wp_load (0.119s)
Debug (bootstrap): Attaching command 'db size' to hook after_wp_load (0.12s)
Debug (bootstrap): Attaching command 'db prefix' to hook after_wp_load (0.121s)
Debug (bootstrap): Attaching command 'db search' to hook after_wp_load (0.122s)
Debug (bootstrap): Attaching command 'db columns' to hook after_wp_load (0.122s)
Debug (commands): Adding command: db (0.123s)
Debug (commands): Adding command: embed (0.126s)
Debug (commands): Adding command: fetch in embed Namespace (0.129s)
Debug (commands): Adding command: provider in embed Namespace (0.13s)
Debug (commands): Adding command: handler in embed Namespace (0.131s)
Debug (commands): Adding command: cache in embed Namespace (0.133s)
Debug (commands): Adding command: comment (0.137s)
Debug (commands): Adding command: meta in comment Namespace (0.14s)
Debug (commands): Adding command: menu (0.143s)
Debug (commands): Adding command: item in menu Namespace (0.146s)
Debug (commands): Adding command: location in menu Namespace (0.148s)
Debug (commands): Deferring command: network meta (0.149s)
Debug (commands): Adding command: option (0.153s)
Debug (commands): Adding command: post (0.159s)
Debug (commands): Adding command: meta in post Namespace (0.162s)
Debug (commands): Adding command: term in post Namespace (0.164s)
Debug (commands): Adding command: post-type (0.166s)
Debug (commands): Adding command: site (0.17s)
Debug (commands): Adding command: meta in site Namespace (0.171s)
Debug (commands): Adding command: option in site Namespace (0.173s)
Debug (commands): Adding command: taxonomy (0.176s)
Debug (commands): Adding command: term (0.18s)
Debug (commands): Adding command: meta in term Namespace (0.182s)
Debug (commands): Adding command: user (0.188s)
Debug (commands): Adding command: application-password in user Namespace (0.193s
)
Debug (commands): Adding command: meta in user Namespace (0.196s)
Debug (commands): Adding command: session in user Namespace (0.198s)
Debug (commands): Adding command: term in user Namespace (0.199s)
Debug (commands): Adding command: network (0.2s)
Debug (hooks): Processing hook "after_add_command:network" with 1 callbacks (0.2
s)
Debug (hooks): On hook "after_add_command:network": Closure in file phar://C:/wp
-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 695 (0.201s)
Debug (commands): Adding command: meta in network Namespace (0.202s)
Debug (commands): Adding command: export (0.204s)
Debug (commands): Adding command: plugin (0.213s)
Debug (commands): Adding command: auto-updates in plugin Namespace (0.216s)
Debug (commands): Adding command: theme (0.225s)
Debug (commands): Adding command: auto-updates in theme Namespace (0.227s)
Debug (commands): Adding command: mod in theme Namespace (0.23s)
Debug (bootstrap): Attaching command 'i18n' to hook before_wp_load (0.231s)
Debug (commands): Adding command: i18n (0.232s)
Debug (bootstrap): Attaching command 'i18n make-pot' to hook before_wp_load (0.2
36s)
Debug (commands): Adding command: make-pot in i18n Namespace (0.236s)
Debug (bootstrap): Attaching command 'i18n make-json' to hook before_wp_load (0.
238s)
Debug (commands): Adding command: make-json in i18n Namespace (0.239s)
Debug (bootstrap): Attaching command 'i18n make-mo' to hook before_wp_load (0.24
1s)
Debug (commands): Adding command: make-mo in i18n Namespace (0.242s)
Debug (bootstrap): Attaching command 'i18n make-php' to hook before_wp_load (0.2
45s)
Debug (commands): Adding command: make-php in i18n Namespace (0.246s)
Debug (bootstrap): Attaching command 'i18n update-po' to hook before_wp_load (0.
248s)
Debug (commands): Adding command: update-po in i18n Namespace (0.251s)
Debug (commands): Adding command: import (0.255s)
Debug (commands): Deferring command: language core (0.26s)
Debug (commands): Deferring command: language plugin (0.262s)
Debug (commands): Deferring command: language theme (0.264s)
Debug (hooks): Immediately invoking on passed hook "after_add_command:site": Clo
sure in file phar://C:/wp-cli/wp-cli.phar/vendor/wp-cli/language-command/languag
e-command.php at line 39 (0.264s)
Debug (commands): Adding command: switch-language in site Namespace (0.266s)
Debug (commands): Adding command: language (0.267s)
Debug (hooks): Processing hook "after_add_command:language" with 3 callbacks (0.
267s)
Debug (hooks): On hook "after_add_command:language": Closure in file phar://C:/w
p-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 695 (0.268s)
Debug (commands): Adding command: core in language Namespace (0.269s)
Debug (hooks): On hook "after_add_command:language": Closure in file phar://C:/w
p-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 695 (0.269s)
Debug (commands): Adding command: plugin in language Namespace (0.27s)
Debug (hooks): On hook "after_add_command:language": Closure in file phar://C:/w
p-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/class-wp-cli.php at line 695 (0.271s)
Debug (commands): Adding command: theme in language Namespace (0.272s)
Debug (bootstrap): Attaching command 'maintenance-mode' to hook after_wp_load (0
.273s)
Debug (commands): Adding command: maintenance-mode (0.274s)
Debug (commands): Adding command: media (0.281s)
Debug (bootstrap): Attaching command 'package' to hook before_wp_load (0.288s)
Debug (commands): Adding command: package (0.29s)
Debug (commands): Adding command: rewrite (0.293s)
Debug (commands): Adding command: rewrite (0.294s)
Debug (commands): Adding command: cap (0.298s)
Debug (commands): Adding command: role (0.302s)
Debug (commands): Adding command: scaffold (0.306s)
Debug (commands): Adding command: search-replace (0.313s)
Debug (bootstrap): Attaching command 'server' to hook before_wp_load (0.315s)
Debug (commands): Adding command: server (0.316s)
Debug (commands): Adding command: shell (0.318s)
Debug (commands): Adding command: super-admin (0.321s)
Debug (commands): Adding command: widget (0.326s)
Debug (commands): Adding command: sidebar (0.327s)
Debug (bootstrap): Processing bootstrap step: WP_CLI\Bootstrap\RegisterFramework
Commands (0.328s)
Debug (bootstrap): Adding framework command: phar://wp-cli.phar/vendor/wp-cli/wp
                        schedules.
  db                    Performs basic database operations using credentials
                        stored in wp-config.php.
  eval                  Executes arbitrary PHP code.
  eval-file             Loads and executes a PHP file.
  export                Exports WordPress content to a WXR file.
  help                  Gets help on WP-CLI, or on a specific command.
  i18n                  Provides internationalization tools for WordPress
                        projects.
  import                Imports content from a given WXR file.
  language              Installs, activates, and manages language packs.
  maintenance-mode      Activates, deactivates or checks the status of the
                        maintenance mode of a site.
                        lists registered image sizes.
  menu                  Lists, creates, assigns, and deletes the active theme's
                        navigation menus.
  network               Perform network-wide operations.
  option                Retrieves and sets site options, including plugin and
                        WordPress settings.
  package               Lists, installs, and removes WP-CLI packages.
  plugin                Manages plugins, including installs, activations, and
                        updates.
  post                  Manages posts, content, and meta.
  post-type             Retrieves details on the site's registered post types.
  rewrite               Lists or flushes the site's rewrite rules, updates the
                        permalink structure.
  role                  Manages user roles, including creating new roles and
                        resetting to defaults.
  scaffold              Generates code for post types, taxonomies, plugins,
                        child themes, etc.
  search-replace        Searches/replaces strings in the database.
  server                Launches PHP's built-in web server for a specific
                        WordPress installation.
                        PHP code.
  sidebar               Lists registered sidebars.
  site                  Creates, deletes, empties, moderates, and lists one or
                        more sites on a multisite installation.
                        installation.
  taxonomy              Retrieves information about registered taxonomies.
  term                  Manages taxonomy terms and term meta, with create,
                        delete, and list commands.
  theme                 Manages themes, including installs, activations, and
                        updates.
  transient             Adds, gets, and deletes entries in the WordPress
                        Transient Cache.
                        meta.
                        sidebars.



GLOBAL PARAMETERS

  --path=<path>
      Path to the WordPress files.

  --url=<url>
      Pretend request came from given URL. In multisite, this argument is how
      the target site is specified.

  --ssh=[<scheme>:][<user>@]<host|container>[:<port>][<path>]
      Perform operation against a remote server over SSH (or a container using
      scheme of "docker", "docker-compose", "docker-compose-run", "vagrant").

  --http=<http>
      Perform operation against a remote WordPress installation over HTTP.

  --user=<id|login|email>
      Set the WordPress user.

  --skip-plugins[=<plugins>]
      Skip loading all plugins, or a comma-separated list of plugins. Note:
      mu-plugins are still loaded.

  --skip-themes[=<themes>]
      Skip loading all themes, or a comma-separated list of themes.

  --skip-packages
      Skip loading all installed packages.

  --require=<path>
      Load PHP file before running the command (may be used more than once).

  --exec=<php-code>
      Execute PHP code before running the command (may be used more than once).

  --context=<context>
      Load WordPress in a given context.

  --[no-]color
      Whether to colorize the output.

  --debug[=<group>]
      Show all PHP errors and add verbosity to WP-CLI output. Built-in groups
      include: bootstrap, commandfactory, and help.

  --prompt[=<assoc>]
      Prompt the user to enter values for all command arguments, or a subset
      specified as comma-separated values.

  --quiet
      Suppress informational messages.

  Run 'wp help <command>' to get more information on a specific command.
`

**Comment by swissspidy** [comment]
There can be a lot of nuances when creating POT files, which is why sharing as much information as possible is important. A GitHub repo or Gist would be easiest. We cannot really provide support otherwise.

**Comment by SamirDeveloper** [comment]
Okey, I understand your position regarding that issue, but tried the `--debug` command like that `C:\wp-cli> php wp-cli.phar i18n make-pot ../wamp64/www/webtips/smoothies/wp-content/plugins/str-sticky-header/ ../wamp64/www/webtips/smoothies/wp-content/plugins/str-sticky-header/lang/potfile.pot --debug` and this just gives the POT file for the str-sticky-header.php file only (which is the main plugin file), bearing in mind that it's parsing the files "admn-view.php" and "tdn.php" that I want it to use for the POT file generation, but it doesn't generate anything from those. 
But when I use that given code line above adding the parameter `--ignore-domain` , it parses everything as the first code line (without that last parameter --ignore-domain), but it generates a POT file from str-sticky-header.php (main plugin file) and admn-view.php (which is the file I want to translate). But the thing is, admn-view.php contains all printf() esc_html_e() functions without any text domain added to them. at the same time, the code line parses tdn.php file (which is the same as admn-view.php, the difference is that tdn.php file contains functions with Text Domain).

How is that possible ? 
I mean for the 1st line code, it parses both "admn-view.php and tdn.php" but it just generate POT file for str-sticky-header.php and not for tdn.php as well. and in  the 2nd line code, it parses both "admn-view.php and tdn.php" but it just generate POT file for "str-sticky-header.php and admn-view.php" and not for tdn.php.

Thank you so much @swisspidy, I appreciate your help !!

**Comment by SamirDeveloper** [comment]
I tried the parameter `--domain="str-sticky-header"` but it just gives exactly the same result without it, i tried this to see whether it will generate POT file from tdn.php (because this file contains translation functions with a text domain)

**Comment by swissspidy** [comment]
There might be a code/syntax issue in tdn.php that causes WP-CLI to fail to extract the strings.

Without a full code sample I‘m afraid we can‘t help further.

**Comment by SamirDeveloper** [comment]
Okey, thanks for the answer again, 
The tdn.php file is exactly the same as admn-view.php, the only difference, is that tdn.php contains text domain inside its translation function (printf() esc_html_e() ...).
But what I noticed, if it's really the same, it has to display the same thing as well, which is not, admn-view.php is displayed well in the plugin admin interface, but when I try to use tdn.php for the same task, it displays the file content, like the PHP and HTML code, which is weird to me, 

What could be the issue in this tdn.php file ?

Thanks @swissspidy

**Comment by SamirDeveloper** [comment]
Just take note that tdn.php was generated using this code line : 

`php add-textdomain.php str-sticky-header ../view/admn-view.php > tdn.php`

As I said before, I generated tdn.php to add text domain to translation functions, 

Is this code line created an issue in the new file tdn.php when it added text domain to each translation function ?

**Comment by swissspidy** [comment]
Yes that is possible. If you‘re file is not working in WordOress then you shoukd figure that out first.

**Comment by SamirDeveloper** [comment]
Thanks @swissspidy ,
Look man, there's no error in the generated tdn.php file, I followed its lines one by one with the naked eye, nothing tricky found, but here's what I've done as well :
- I created a new file (simple file creation, right click on mouse -> new file) with the same name "tdn.php", 
- I placed it under str-sticky-header/view/ path, 
- I copied pasted the old tdn.php content file generated using this command line `php add-textdomain.php str-sticky-header ../view/admn-view.php > tdn.php` to the new tdn.php file,
- I tried to display the new tdn.php file content in the plugin admin interface, it worked perfectly,
- I tried to generate POT file using the new tdn.php created file, and it worked perfectly.

So the conclusion : the command line used to generate the text domain file (tdn.php) is the issue, it doesn't allow anyone to display or manipulate that generated file, I don't know why, but that's my conclusion. 

I have a last question, will I need that old tdn.php file ? or should I just go and replace it with the new file ? 
And by the way, I can generate another tdn.php file in case I need it.

Thank you @swissspidy

**Comment by swissspidy** [comment]
> So the conclusion : the command line used to generate the text domain file (tdn.php) is the issue, it doesn't allow anyone to display or manipulate that generated file, I don't know why, but that's my conclusion.

Probably. I don't know what script you used, so can't say more.

> I have a last question, will I need that old tdn.php file ? or should I just go and replace it with the new file ?

I don't know why you would need to keep a broken file that doesn't work.
