### ISSUE TITLE
How to include this into your wp-cli.phar?

### ISSUE THREAD

**Issue by carli2** [wp-cli/i18n-command#416]
Hi,

I'm using wp-cli.phar and don't know how to add this addon. Also, wp i18n dosen't work according to https://github.com/swissspidy/gutenberg-i18n-block/issues/6, so I want to try this.

**Comment by swissspidy** [comment]
This package is included with WP-CLI itself, no additional installation necessary.

To install the latest version of this package over what's included in WP-CLI, run:

```
wp package install git@github.com:wp-cli/i18n-command.git
```

**Comment by carli2** [comment]
But then, I still get the error `Success: Created 0 files.` when trying to generate .json from .po files. I am using Gutenberg Block system, so I cannot hook onto `wp_set_script_translations`

**Comment by swissspidy** [comment]
Well that's a different question entirely then.

It sounds like you might not have any JS string references in your PO file. If there's no strings in it, there's nothing to generate.

If you share your repository here I can try to take a look to see what's going on.

With that said, please note that GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. The easiest way to get support is to join us in the [`#cli`](https://wordpress.slack.com/messages/C02RP4T41) channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/). So please share your details there :-)

**Comment by carli2** [comment]
I don't think the .po format allows for JS string references. My .po files are full of msgids and msgtexts but still no json files generated.

Here's my workaround:
```
	msgfmt erechnung-checker-de_DE.po -o erechnung-checker-de_DE.mo
	po2json -p erechnung-checker-de_DE.po erechnung-checker-de_DE.json -d erechnung-checker
	(echo '{"locale_data": {"messages": ' && (cat erechnung-checker-de_DE.json | grep -v 'null,') && echo "}}" ) > erechnung-checker-de_DE-create-block-erechnung-checker-view-script.json
	rm erechnung-checker-de_DE.json
```
to replace the non-working make-json and
```
	// don't know what's the proper way to add translation; this hacked shit works
	$plugin_dir = basename( dirname( __FILE__ ) );
	wp_set_script_translations( 'create-block-erechnung-checker-view-script', 'erechnung-checker', 'wp-content/plugins/' . $plugin_dir . '/languages');
```
to workaround that includes/block.php does not set a filename block scripts with i18n dependency

**Comment by swissspidy** [comment]
> I don't think the .po format allows for JS string references. My .po files are full of msgids and msgtexts but still no json files generated.

It only generates a JSON file for strings that are found in JS files. So for example if your PO file contains this:

```
 #: foo-plugin.js:15
msgid "Foo Plugin"
msgstr "Foo Plugin"
```

It will create a `foo-plugin-de_DE-56746e49c6485323d16a717754b7447e.json` file, where `56746e49c6485323d16a717754b7447e` is the md5 hash of `foo-plugin.js`.

Your code snippets are unfortunately not very helpful for assisting you. If you want, you can send me the link to your GitHub repository and I can take a look.

I also recommend reading https://pascalbirchler.com/internationalization-in-wordpress-5-0/ to learn more about how this all is supposed to work.

**Comment by carli2** [comment]
What does 'found in JS files' mean exactly? The strings that have to be translated of course occur in view.js which is referenced in block.json. But how does this detection algorithm work at all and how to I add strings that are not found automatically?

**Comment by swissspidy** [comment]
> What does 'found in JS files' mean exactly? The strings that have to be translated of course occur in view.js which is referenced in block.json. But how does this detection algorithm work at all and how to I add strings that are not found automatically?

In short, tools like WP-CLI scan your PHP and JavaScript files for usage of i18n functions like `__( 'Please translate me', 'my-plugin' )` and then adds the `Please translate me` string to the PO file, together with the file & line where it was found.

Commands like `wp i18n make-json` then can take your PO file and create JSON files for every single JS file where such strings were found.

There's great documentation available at https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/, https://developer.wordpress.org/plugins/internationalization/localization/, and the blog post I linked to above. https://pascalbirchler.com/text-domain-wordpress-internationalization/ is also useful.
So "zero documentation" is absolutely not true.

**Comment by carli2** [comment]
I managed to extract all msgids from .js sources now, too (had to remove a helper function) - the problem that make-json does not create any file still exists.

Is there some hidden convention how I must name the folders or the .pot file for this in order to work?

**Comment by carli2** [comment]
Yes, these old documentations work for old plugin style, but not for gutenberg blocks baked with wp-scripts. That's what I had to read by myself from source code (and still no clue how to do it "properly")

**Comment by swissspidy** [comment]
It works just the same for Gutenberg blocks, there is no secret or anything.

Again, feel free to share your repository link and I am happy to help you fix this. That‘s faster than this back and forth. You can also send it privately via Slack if you want.

**Comment by carli2** [comment]
So where do I have to place the language files for both JS and PHP so that wordpress finds them automatically? Or is both `wp_set_script_translations` and load_plugin_textdomain necessary?

**Comment by swissspidy** [comment]
Both are necessary to tell WordPress where the translations are stored

**Comment by carli2** [comment]
Ok thank you so much. I think I will close this ticket and leave it as is. I got my translations running with some tweaks and reading source code to find out how the super-duper automatic script names it's scripts but it works now.
