### ISSUE TITLE
Add support for `styles` labels set in block.json

### ISSUE THREAD

**Issue by benoitchantre** [wp-cli/i18n-command#419]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

When you set some block styles in block.json and use the `wp i18n make-pot` command, the generated .pot file doesn't contains the label strings.

Example:
```json
"styles": [
	{
		"name": "default",
		"label": "Default",
		"isDefault": true
	},
	{
		"name": "subscription",
		"label": "Subscription"
	}
],
```

_Default_ and _Subscription_ are missing from the .pot file.

**Describe the solution you'd like**

These strings should be part of the .pot file.

**Comment by swissspidy** [comment]
Hey @benoitchantre 👋 

That sounds strange. What version of `wp i18n` are you using? You can check using `wp cli info` and `wp package list`.

This field has long been translatable (for over 4 years) and [according to this passing test](https://github.com/wp-cli/i18n-command/blob/065bb3758fcbff922f1b7a01ab702aab0da79803/features/makepot.feature#L3180-L3279) the string extraction should actually be working.

Do you perhaps have some code, e.g. a GitHub Gist or repository, where this can be reproduced?

**Comment by benoitchantre** [comment]
Hi @swissspidy,

My bad, there was a mistake on my side: I had an inconsistent textdomain set in block.json.

After having fixed that value, I now the the expected .pot file
