### ISSUE TITLE
Add parameters for Language-Team header

### ISSUE THREAD

**Issue by greatislander** [wp-cli/i18n-command#48]
When running `wp i18n make-pot`, the `Language-Team` header is set to `LANGUAGE <LL@li.org>`. Adding optional parameters for `--language_team` and `--language_team_address` (URL or email) would allow users to supply their information to provide real information for this `.pot` header.

**Comment by GaryJones** [comment]
For `.pot` files, this can (and IMO, should) be left as placeholders. It is assumed that this template file is created by the author or team who created the plugin or theme.

Only once the file is copied to be a `.po` file does it make sense for that field to be populated, since that refers to the team who are handling that language. 

https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html

If there was a command like `wp i18n make-po` that copied `.pot` to `.po`, then yes, a parameter like you've suggested would make sense.

**Comment by schlessera** [comment]
Ah, so this is meant to be used for the translators, not the original developer then. That makes sense.

What would such a `make-po` command do, then? Copy and replace placeholders only, or are other steps involved?

**Comment by GaryJones** [comment]
> Ah, so this is meant to be used for the translators, not the original developer then.

Just to re-iterate this further, see https://developer.wordpress.org/themes/functionality/localization/#po-portable-object-files (my emphasis):

> The result is a PO file with the same format as a POT, but with translations and **language specific headers**. 

----

> What would such a `make-po` command do, then?

Off the top of my head, a call like `wp i18n make-po path/to/pot-file-directory --locale=en_GB --language-team="British English <en-gb@my-plugin.com>" --last-translator="Gary Jones <gary@garyjones.tld>"`:

- Optionally verify that the required locale parameter is valid (either the format, or checked against a known list if one is available).
- Copy `.pot` to correct `.po` filename for the item type:
    - `en_GB.po` for [themes](https://developer.wordpress.org/themes/functionality/localization/#translate-po-file).
    - `myplugin-en_GB.po` for [plugins](https://developer.wordpress.org/plugins/internationalization/localization/#translate-po-file).
- Replace the language header placeholder, if the optional `language-team` parameter was passed in.
- Replace the last translator placeholder, if the optional `last-translator` parameter was passed in.
- Update the `PO-Revision-Date` value.

Note that one further extension would be to have more flexibility on paths - the `Languages` directory referenced in plugin and theme headers only needs to contain the `.mo` files (the generation of which could be a separate command if it isn't already, though that has a few more dependencies) - the `.pot` and `.po` files could technically live somewhere else entirely.

**Comment by greatislander** [comment]
I'll close this then. Thanks for the clarification, @GaryJones.
