### ISSUE TITLE
Add parameters for Last-Translator header

### ISSUE THREAD

**Issue by greatislander** [wp-cli/i18n-command#49]
When running `wp i18n make-pot`, the `Last-Translator` header is set to `FULL NAME <EMAIL@ADDRESS>`. Adding optional parameters for `--last_translator` and `--last_translator_address` (email) would allow users to supply their information to provide real information for this `.pot` header.

**Comment by GaryJones** [comment]
See my comment at https://github.com/wp-cli/i18n-command/issues/48#issuecomment-406511262.
