### ISSUE TITLE
Add X-Generator header to resulting POT file

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/i18n-command#53]
A header like `X-Generator: WP-CLI 2.0.0` (using `WP_CLI_VERSION`) could be useful for developers to see where the POT file is coming from. See https://github.com/wp-cli/i18n-command/issues/50#issuecomment-407399301.

Even better would be if we could also get the package's version, but I'm not sure how feasible that is.

**Comment by vslavik** [comment]
> Even better would be if we could also get the package's version

I'm not sure what you mean by that. If you're referring to some dependencies of WP-CLI, then I think it would be superfluous — everybody uses just `<tool>[ <version>]` for this header. If you mean the thing the POT is being generated for, then it shouldn't affect `X-Generator` and should go into (only) the `Project-Id-Version` header.

**Comment by swissspidy** [comment]
I was thinking of „WP-CLI i18n-command 1.0.0“ instead of „WP-CLI 2.0.0“

**Comment by swissspidy** [comment]
@schlessera Is there a way I can get this command's version in PHP? I think it makes more sense to have `X-Generator: WP-CLI i18n-command 1.0.0` instead of `X-Generator: WP-CLI 2.0.0`.

**Comment by schlessera** [comment]
@swissspidy, re. package version, there's three scenarios:
1. For the Phar bundle, you'll find a file inside the Phar called `COMPOSER_VERSIONS`: https://github.com/wp-cli/wp-cli/blob/v1.5.1/utils/make-phar.php#L288
2. For commands installed through the package manager, you'd have to get it from the Composer package information through the package manager: https://github.com/wp-cli/package-command/blob/master/src/Package_Command.php#L770-L781
3. For packages installed via regular Composer, you'll have to parse the Composer information yourself.

I suggest merging the current code as-is, and create a new issue to discuss adding a `wp package version` command to abstract the above away.

**Comment by swissspidy** [comment]
Opened https://github.com/wp-cli/package-command/issues/85 and closing this for now.
