### ISSUE TITLE
Use unit tests for  `--include` and `--exclude` syntax instead of functional tests

### ISSUE THREAD

**Issue by schlessera** [wp-cli/i18n-command#70]
Some of tests, including but maybe not limited to `--include` and `--exclude` syntax tests, would be a better fit as unit tests. These would be more reliable and much faster.

**Comment by swissspidy** [comment]
There are now some unit tests since #83.

We might clean up the folder structure for them at some point though.

Also, there are still some Behat tests for these arguments, but I think we can keep them for now as it doesn't matter much.
