### ISSUE TITLE
Uncaught Error: Class 'Peast\Peast' not found

### ISSUE THREAD

**Issue by westonruter** [wp-cli/i18n-command#73]
I'm trying `wp i18n make-pot .` on the AMP plugin and I'm getting an error:

```
Plugin file detected.
PHP Fatal error:  Uncaught Error: Class 'Peast\Peast' not found in phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/JsFunctionsScanner.php:40
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/JsCodeExtractor.php(34): WP_CLI\I18n\JsFunctionsScanner->saveGettextFunctions(Object(Gettext\Translations), Array)
#1 phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/IterableCodeExtractor.php(59): WP_CLI\I18n\JsCodeExtractor::fromString('/**\n * Adds an ...', Object(Gettext\Translations), Array)
#2 phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/IterableCodeExtractor.php(86): WP_CLI\I18n\JsCodeExtractor::fromFile(Array, Object(Gettext\Translations), Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/MakePotCommand.php(540): WP_CLI\I18n\JsCodeExtractor::fromDirectory('/srv/www/wordpr...', Object(Gettext\Translations), Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/MakePotCommand.php(217): WP_CLI\I18n\MakePotCommand->extract_strings()
#5 [internal function]: WP_C in phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/JsFunctionsScanner.php on line 40
```

I'm using WP-CLI v2.0.0 installed via Phar.

**Comment by westonruter** [comment]
I tried installing the i18n-command package, thinking there was a conflict, and then I get another error:

```
Plugin file detected.
PHP Fatal error:  Uncaught Error: Class 'Gettext\Translations' not found in phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/MakePotCommand.php:340
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/MakePotCommand.php(215): WP_CLI\I18n\MakePotCommand->handle_arguments(Array, Array)
#1 [internal function]: WP_CLI\I18n\MakePotCommand->__invoke(Array, Array)
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)
#3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(365): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(388): WP_CLI\Runner->run_command(Array, Array)
#7 phar:///usr/local/bin/wp/vendor in phar:///usr/local/bin/wp/vendor/wp-cli/i18n-command/src/MakePotCommand.php on line 340
```

I've removed the `~/.wp-cli` directory entirely.

**Comment by schlessera** [comment]
Thanks for the report, @westonruter!
I will investigate this promptly.

**Comment by schlessera** [comment]
I blame the lack of sleep. The Phar compilation did not include the vendor folders specifically required for the `i18n-command`. And we didn't notice that because the test suite didn't include the feature tests for the `i18n-command`.

I guess this makes it obvious we need a checklist for bundling a new command (correctly).

I'll push a hotfix shortly. In the meantime, if you want to run tests, you can clone the `wp-cli/i18n-command` and run it from its `vendor/bin/wp` once you've done a `composer install` inside.

**Comment by schlessera** [comment]
@westonruter I've built a new nightly that fixes this problem.

You can switch to the latest nightly with the `wp cli update --nightly` command.

Please let me know whether that version works for you now.

**Comment by danielbachhuber** [comment]
@schlessera Would this have been caught if `wp-cli/automated-tests` was passing? https://github.com/wp-cli/automated-tests#wp-cli-automated-tests

**Comment by schlessera** [comment]
@danielbachhuber Tests were passing. But I didn't realize that `wp-cli/i18n-command` was being skipped from the tests.

That's why I noted I need a checklist for adding a new command to the bundle. I need to make sure that the automated test suite actually includes that new command as well.

**Comment by danielbachhuber** [comment]
> But I didn't realize that wp-cli/i18n-command was being skipped from the tests.

Ah, that's the sticky wicket :)

> That's why I noted I need a checklist for adding a new command to the bundle. I need to make sure that the automated test suite actually includes that new command as well.

Cool, sounds good.

**Comment by westonruter** [comment]
Thanks guys. Fixed.
