### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '[' in .../MakePotCommand.php on line 29

### ISSUE THREAD

**Issue by soupmagnet** [wp-cli/i18n-command#79]
**Summary**
We have multiple web hosting accounts with the same web host, one of which has an installation of WP-CLI that is misbehaving.  

Recently, I installed WP-CLI in a new hosting environment, but it failed to start, due to the following error...

`PHP Parse error:  syntax error, unexpected '[' in phar:///[redacted]/wp/vendor/wp-cli/i18n-command/src/MakePotCommand.php on line 29`

**Steps to reproduce**
The same error is generated regardless of what command is used...essentially, WP-CLI fails to start. 

 What's interesting is the fact that we have several other sites hosted at the same web host using the same hosting plan (same server specs, software, etc.).  Each hosting account is running PHP 7.0.30 with the default extensions loaded, and running WP-CLI version 2.0.0.  Each account is hosting a WordPress website with a custom built theme, but all relatively similar in development to the others.  

I just can't for the life of me figure out why we have multiple instances of WP-CLI, each hosted in practically identical environments, but only the one is throwing a syntax error. 

**Environment**

CentOS release 6.10 (Final)
Apache/2.2.34 (Unix) / PHP 7.0.30

Loaded extensions - apc, bz2, calendar,  ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconvi magick, imap, intl, json, libxml, mbstring, mcrypt, memcache, mysqli, mysqlnd, openssl, pcntl, pcre, PDO, pdo_mysql, pdo_sqlite, Phar,  posix, pspell, readline, redis, Reflection, session

The only real difference between the hosting environments that I can find is on the affected server, which is running Phar 2.0.1, whereas on the other accounts where WP-CLI is functioning properky, are running Phar 2.0.2, and all are running the same API version (1.1.1).

TIA

**Comment by schlessera** [comment]
@soupmagnet You need to check what PHP binary is being used to run WP-CLI, because the above issue results from the code being run on PHP 5.3. WP-CLI has bumped its minimum requirement to PHP 5.4+ from WP-CLI v2.0.0 on.

**Comment by soupmagnet** [comment]
Thank you, @schlessera.  It turned out to be PHP-CLI that was still running the outdated version.  False alarm, but thanks anyway.
