### ISSUE TITLE
Don't set PO-Revision-Date to POT build time

### ISSUE THREAD

**Issue by ocean90** [wp-cli/i18n-command#90]
There are two headers, `POT-Creation-Date` and `PO-Revision-Date`, which are [set by default to `date('c')`](https://github.com/oscarotero/Gettext/blob/545f716f08338030d2d0d35a1835d04a9d4f18ed/src/Translations.php#L132-L134). Since no PO file created the header is misleading

`makepot.php` is using `date( 'Y') . '-MO-DA HO:MI+ZONE' `. The [documentation](https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html) says:

> **PO-Revision-Date**
> You don’t need to fill this in. It will be filled by the PO file editor when you save the file.

**Comment by swissspidy** [comment]
With a quick search I also stumbled upon `"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"`, which probably is even better.
